apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: goquizvibe
spec:
  selector:
    app: backend
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: grpc
      port: 9100
      targetPort: 9100
