package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/goquizvibe/models"
)

func (s *MemoryStore) SeedMathQuizzes(teacherID uuid.UUID) {
	grade5ID := uuid.New()
	grade6ID := uuid.New()
	grade7ID := uuid.New()

	s.Quizzes[grade5ID] = &models.Quiz{
		ID:          grade5ID,
		Title:       "Математика 5 класс: Дроби и десятичные дроби",
		Description: "Тест на знание обыкновенных и десятичных дробей",
		Subject:     "Математика",
		Grade:       5,
		CreatedBy:   teacherID,
		Status:      models.QuizStatusAvailable,
		TimeLimit:   30,
		CreatedAt:   time.Now(),
		Questions: []models.Question{
			{
				ID:            uuid.New(),
				Text:          "Чему равна сумма 1/4 + 1/4?",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"1/2", "2/4", "1/8", "1"},
				CorrectAnswer: "1/2",
				Explanation:   "При сложении дробей с одинаковым знаменателем складываем числители: 1+1=2, получаем 2/4 = 1/2",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Переведите десятичную дробь 0.75 в обыкновенную дробь.",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "3/4",
				Explanation:   "0.75 = 75/100 = 3/4 (сокращаем на 25)",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Вычислите: 2.5 + 1.3",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"3.8", "3.7", "3.9", "4.0"},
				CorrectAnswer: "3.8",
				Explanation:   "Десятые доли: 0.5 + 0.3 = 0.8, целые: 2 + 1 = 3",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Заполните пропуск: 1/3 = ___/9",
				Type:          models.QuestionTypeFill,
				CorrectAnswer: "3",
				Explanation:   "Чтобы 1/3 привести к знаменателю 9, нужно и числитель, и знаменатель умножить на 3",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Чему равна разность 3/5 - 1/5?",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"2/5", "1/5", "2/10", "4/5"},
				CorrectAnswer: "2/5",
				Explanation:   "При вычитании дробей с одинаковым знаменателем вычитаем числители: 3-1=2",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Переведите дробь 1/8 в десятичную дробь.",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "0.125",
				Explanation:   "1/8 = 0.125, так как 1 ÷ 8 = 0.125",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Какое число больше: 0.6 или 3/5?",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"Они равны", "0.6", "3/5", "Невозможно сравнить"},
				CorrectAnswer: "Они равны",
				Explanation:   "3/5 = 0.6, это одно и то же число",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Вычислите: 5 - 1.75",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "3.25",
				Explanation:   "5.00 - 1.75 = 3.25",
				Points:        10,
			},
		},
	}

	s.Quizzes[grade6ID] = &models.Quiz{
		ID:          grade6ID,
		Title:       "Математика 6 класс: Пропорции и отрицательные числа",
		Description: "Тест на знание пропорций, координат и действий с отрицательными числами",
		Subject:     "Математика",
		Grade:       6,
		CreatedBy:   teacherID,
		Status:      models.QuizStatusAvailable,
		TimeLimit:   30,
		CreatedAt:   time.Now(),
		Questions: []models.Question{
			{
				ID:            uuid.New(),
				Text:          "Решите уравнение: x + 5 = 2",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "-3",
				Explanation:   "x = 2 - 5 = -3",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Чему равно произведение (-3) × (-4)?",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"12", "-12", "7", "-7"},
				CorrectAnswer: "12",
				Explanation:   "При умножении двух отрицательных чисел результат положительный: (-3)×(-4)=12",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Какое число соответствует точке A на координатной прямой? (изображение точки A слева от 0 на расстоянии 3 делений)",
				Type:          models.QuestionTypeFill,
				CorrectAnswer: "-3",
				Explanation:   "Точка слева от нуля на расстоянии 3 единиц имеет координату -3",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Найдите x из пропорции: 2/x = 4/10",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"5", "4", "2", "8"},
				CorrectAnswer: "5",
				Explanation:   "x = 2 × 10 / 4 = 20/4 = 5",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Чему равна сумма (-7) + 3?",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "-4",
				Explanation:   "-7 + 3 = -4 (движемся вправо по числовой прямой на 3 единицы)",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Вычислите: |-5| + |3|",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"8", "2", "-2", "-8"},
				CorrectAnswer: "8",
				Explanation:   "|-5| = 5, |3| = 3, значит 5 + 3 = 8",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Какой знак нужно поставить: -8 ___ -5 (чтобы получить верное утверждение)",
				Type:          models.QuestionTypeFill,
				CorrectAnswer: "<",
				Explanation:   "-8 меньше -5, так как -8 лежит левее на числовой прямой",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Решите: (-10) ÷ (-2)",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"5", "-5", "20", "-20"},
				CorrectAnswer: "5",
				Explanation:   "При делении двух отрицательных чисел результат положительный: (-10)÷(-2)=5",
				Points:        15,
			},
		},
	}

	s.Quizzes[grade7ID] = &models.Quiz{
		ID:          grade7ID,
		Title:       "Математика 7 класс: Одночлены и многочлены",
		Description: "Тест на знание одночленов, многочленов и формул сокращённого умножения",
		Subject:     "Математика",
		Grade:       7,
		CreatedBy:   teacherID,
		Status:      models.QuizStatusAvailable,
		TimeLimit:   30,
		CreatedAt:   time.Now(),
		Questions: []models.Question{
			{
				ID:            uuid.New(),
				Text:          "Упростите: 3x² × 2x",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "6x³",
				Explanation:   "3×2=6, x²×x=x³ (при умножении степени складываются)",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Раскройте скобки: (x + 3)²",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"x² + 6x + 9", "x² + 9", "x² + 6x + 6", "x² + 3x + 9"},
				CorrectAnswer: "x² + 6x + 9",
				Explanation:   "По формуле (a+b)² = a² + 2ab + b²: x² + 2·x·3 + 3² = x² + 6x + 9",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Приведите подобные слагаемые: 5a + 3b - 2a + b",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "3a + 4b",
				Explanation:   "5a - 2a = 3a; 3b + b = 4b",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Чему равна степень одночлена 7x³y²?",
				Type:          models.QuestionTypeFill,
				CorrectAnswer: "5",
				Explanation:   "Степень одночлена = сумма степеней всех переменных: 3 + 2 = 5",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Разложите на множители: x² - 16",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"(x-4)(x+4)", "(x-8)(x+8)", "(x-4)²", "(x+4)²"},
				CorrectAnswer: "(x-4)(x+4)",
				Explanation:   "x² - 16 = x² - 4² = (x-4)(x+4) по формуле разности квадратов",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Выполните умножение: (x - 2)(x + 3)",
				Type:          models.QuestionTypeOpen,
				CorrectAnswer: "x² + x - 6",
				Explanation:   "(x-2)(x+3) = x·x + x·3 - 2·x - 2·3 = x² + 3x - 2x - 6 = x² + x - 6",
				Points:        15,
			},
			{
				ID:            uuid.New(),
				Text:          "Какое выражение называется одночленом?",
				Type:          models.QuestionTypeChoice,
				Options:       []string{"Произведение чисел и переменных", "Сумма одночленов", "Выражение с делением на переменную", "Уравнение"},
				CorrectAnswer: "Произведение чисел и переменных",
				Explanation:   "Одночлен — это произведение чисел, переменных и их степеней",
				Points:        10,
			},
			{
				ID:            uuid.New(),
				Text:          "Упростите: (2x)³",
				Type:          models.QuestionTypeFill,
				CorrectAnswer: "8x³",
				Explanation:   "(2x)³ = 2³ · x³ = 8x³",
				Points:        15,
			},
		},
	}
}
