apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: goquizvibe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          ports:
            - containerPort: 9000
          args: ["server", "/data", "--console-address", ":9001"]
          envFrom:
            - configMapRef:
                name: goquizvibe-config
            - secretRef:
                name: goquizvibe-secrets
          volumeMounts:
            - name: minio-data
              mountPath: /data
          livenessProbe:
            exec:
              command: ["mc", "ready", "local"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc