apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: goquizvibe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18.3-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: goquizvibe-config
                optional: true
            - secretRef:
                name: goquizvibe-secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "goquizvibe"]
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "goquizvibe"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc