// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_permissions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAssetPermissionsByAsset = `-- name: DeleteAssetPermissionsByAsset :exec
DELETE FROM asset_permissions WHERE asset_type = $1 AND asset_id = $2
`

type DeleteAssetPermissionsByAssetParams struct {
	AssetType string    `json:"asset_type"`
	AssetID   uuid.UUID `json:"asset_id"`
}

func (q *Queries) DeleteAssetPermissionsByAsset(ctx context.Context, arg DeleteAssetPermissionsByAssetParams) error {
	_, err := q.db.Exec(ctx, deleteAssetPermissionsByAsset, arg.AssetType, arg.AssetID)
	return err
}

const getAccessibleAssetIDs = `-- name: GetAccessibleAssetIDs :many
SELECT DISTINCT ap.asset_id FROM asset_permissions ap
WHERE ap.asset_type = $1
AND (
    (ap.recipient_type = 'user' AND ap.recipient_id = $2)
    OR (ap.recipient_type = 'group' AND ap.recipient_id = ANY($3::uuid[]))
)
`

type GetAccessibleAssetIDsParams struct {
	AssetType   string      `json:"asset_type"`
	RecipientID uuid.UUID   `json:"recipient_id"`
	Column3     []uuid.UUID `json:"column_3"`
}

func (q *Queries) GetAccessibleAssetIDs(ctx context.Context, arg GetAccessibleAssetIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAccessibleAssetIDs, arg.AssetType, arg.RecipientID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var asset_id uuid.UUID
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetPermissions = `-- name: GetAssetPermissions :many
SELECT ap.id, ap.asset_type, ap.asset_id, ap.permission, ap.recipient_type, ap.recipient_id, ap.grantor_id, ap.created_at,
       CASE WHEN ap.recipient_type = 'user' THEN u.name ELSE g.name END as recipient_name
FROM asset_permissions ap
LEFT JOIN users u ON ap.recipient_type = 'user' AND ap.recipient_id = u.id
LEFT JOIN user_groups g ON ap.recipient_type = 'group' AND ap.recipient_id = g.id
WHERE ap.asset_type = $1 AND ap.asset_id = $2
ORDER BY ap.permission DESC, ap.created_at ASC
`

type GetAssetPermissionsParams struct {
	AssetType string    `json:"asset_type"`
	AssetID   uuid.UUID `json:"asset_id"`
}

type GetAssetPermissionsRow struct {
	ID            uuid.UUID   `json:"id"`
	AssetType     string      `json:"asset_type"`
	AssetID       uuid.UUID   `json:"asset_id"`
	Permission    interface{} `json:"permission"`
	RecipientType interface{} `json:"recipient_type"`
	RecipientID   uuid.UUID   `json:"recipient_id"`
	GrantorID     uuid.UUID   `json:"grantor_id"`
	CreatedAt     time.Time   `json:"created_at"`
	RecipientName interface{} `json:"recipient_name"`
}

func (q *Queries) GetAssetPermissions(ctx context.Context, arg GetAssetPermissionsParams) ([]GetAssetPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getAssetPermissions, arg.AssetType, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetPermissionsRow{}
	for rows.Next() {
		var i GetAssetPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetType,
			&i.AssetID,
			&i.Permission,
			&i.RecipientType,
			&i.RecipientID,
			&i.GrantorID,
			&i.CreatedAt,
			&i.RecipientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupAssetPermissions = `-- name: GetGroupAssetPermissions :many
SELECT id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at FROM asset_permissions
WHERE recipient_type = 'group' AND recipient_id = ANY($1::uuid[])
`

func (q *Queries) GetGroupAssetPermissions(ctx context.Context, dollar_1 []uuid.UUID) ([]AssetPermission, error) {
	rows, err := q.db.Query(ctx, getGroupAssetPermissions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetPermission{}
	for rows.Next() {
		var i AssetPermission
		if err := rows.Scan(
			&i.ID,
			&i.AssetType,
			&i.AssetID,
			&i.Permission,
			&i.RecipientType,
			&i.RecipientID,
			&i.GrantorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAssetPermissions = `-- name: GetUserAssetPermissions :many
SELECT id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at FROM asset_permissions
WHERE recipient_type = 'user' AND recipient_id = $1
`

func (q *Queries) GetUserAssetPermissions(ctx context.Context, recipientID uuid.UUID) ([]AssetPermission, error) {
	rows, err := q.db.Query(ctx, getUserAssetPermissions, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetPermission{}
	for rows.Next() {
		var i AssetPermission
		if err := rows.Scan(
			&i.ID,
			&i.AssetType,
			&i.AssetID,
			&i.Permission,
			&i.RecipientType,
			&i.RecipientID,
			&i.GrantorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermission = `-- name: GrantPermission :one
INSERT INTO asset_permissions (id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (asset_type, asset_id, recipient_type, recipient_id, permission) DO UPDATE SET grantor_id = $7
RETURNING id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at
`

type GrantPermissionParams struct {
	ID            uuid.UUID   `json:"id"`
	AssetType     string      `json:"asset_type"`
	AssetID       uuid.UUID   `json:"asset_id"`
	Permission    interface{} `json:"permission"`
	RecipientType interface{} `json:"recipient_type"`
	RecipientID   uuid.UUID   `json:"recipient_id"`
	GrantorID     uuid.UUID   `json:"grantor_id"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) (AssetPermission, error) {
	row := q.db.QueryRow(ctx, grantPermission,
		arg.ID,
		arg.AssetType,
		arg.AssetID,
		arg.Permission,
		arg.RecipientType,
		arg.RecipientID,
		arg.GrantorID,
		arg.CreatedAt,
	)
	var i AssetPermission
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.AssetID,
		&i.Permission,
		&i.RecipientType,
		&i.RecipientID,
		&i.GrantorID,
		&i.CreatedAt,
	)
	return i, err
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS(
    SELECT 1 FROM asset_permissions
    WHERE asset_type = $1 AND asset_id = $2
    AND recipient_type = $3 AND recipient_id = $4
    AND permission = $5
)
`

type HasPermissionParams struct {
	AssetType     string      `json:"asset_type"`
	AssetID       uuid.UUID   `json:"asset_id"`
	RecipientType interface{} `json:"recipient_type"`
	RecipientID   uuid.UUID   `json:"recipient_id"`
	Permission    interface{} `json:"permission"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.AssetType,
		arg.AssetID,
		arg.RecipientType,
		arg.RecipientID,
		arg.Permission,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasPermissionLevel = `-- name: HasPermissionLevel :one
SELECT EXISTS(
    SELECT 1 FROM asset_permissions
    WHERE asset_type = $1 AND asset_id = $2
    AND recipient_type = $3 AND recipient_id = $4
    AND (
        ($5 = 'owner' AND asset_permission = 'owner')
        OR ($5 = 'write' AND asset_permission IN ('owner', 'write'))
        OR ($5 = 'read')
    )
)
`

type HasPermissionLevelParams struct {
	AssetType     string      `json:"asset_type"`
	AssetID       uuid.UUID   `json:"asset_id"`
	RecipientType interface{} `json:"recipient_type"`
	RecipientID   uuid.UUID   `json:"recipient_id"`
	Column5       interface{} `json:"column_5"`
}

func (q *Queries) HasPermissionLevel(ctx context.Context, arg HasPermissionLevelParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermissionLevel,
		arg.AssetType,
		arg.AssetID,
		arg.RecipientType,
		arg.RecipientID,
		arg.Column5,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokePermission = `-- name: RevokePermission :exec
DELETE FROM asset_permissions
WHERE asset_type = $1 AND asset_id = $2 AND permission = $3 AND recipient_type = $4 AND recipient_id = $5
`

type RevokePermissionParams struct {
	AssetType     string      `json:"asset_type"`
	AssetID       uuid.UUID   `json:"asset_id"`
	Permission    interface{} `json:"permission"`
	RecipientType interface{} `json:"recipient_type"`
	RecipientID   uuid.UUID   `json:"recipient_id"`
}

func (q *Queries) RevokePermission(ctx context.Context, arg RevokePermissionParams) error {
	_, err := q.db.Exec(ctx, revokePermission,
		arg.AssetType,
		arg.AssetID,
		arg.Permission,
		arg.RecipientType,
		arg.RecipientID,
	)
	return err
}

const setOwnerPermission = `-- name: SetOwnerPermission :one
INSERT INTO asset_permissions (id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at)
VALUES ($1, $2, $3, 'owner', 'user', $4, $4, $5)
ON CONFLICT (asset_type, asset_id, recipient_type, recipient_id, permission) DO UPDATE SET grantor_id = $4
RETURNING id, asset_type, asset_id, permission, recipient_type, recipient_id, grantor_id, created_at
`

type SetOwnerPermissionParams struct {
	ID          uuid.UUID `json:"id"`
	AssetType   string    `json:"asset_type"`
	AssetID     uuid.UUID `json:"asset_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) SetOwnerPermission(ctx context.Context, arg SetOwnerPermissionParams) (AssetPermission, error) {
	row := q.db.QueryRow(ctx, setOwnerPermission,
		arg.ID,
		arg.AssetType,
		arg.AssetID,
		arg.RecipientID,
		arg.CreatedAt,
	)
	var i AssetPermission
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.AssetID,
		&i.Permission,
		&i.RecipientType,
		&i.RecipientID,
		&i.GrantorID,
		&i.CreatedAt,
	)
	return i, err
}
