DROP TABLE IF EXISTS quiz_sessions;
DROP TABLE IF EXISTS user_answers;
DROP TABLE IF EXISTS quiz_attempts;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS question_type;
DROP TYPE IF EXISTS quiz_status;
DROP TYPE IF EXISTS role;