// Code generated by gettextcodegen. DO NOT EDIT.

package locales

import (
	"path/filepath"
	"runtime"

	"github.com/leonelquinteros/gotext"
)

type Locale string

const (
	LocaleInvalid Locale = ""
	LocaleEn      Locale = "en"
	LocaleRu      Locale = "ru"
)

type Translator interface {
	// "Actions"
	Actions() string
	// "Add"
	Add() string
	// "Add Option"
	AddOption() string
	// "Add Question"
	AddQuestion() string
	// "Admin"
	Admin() string
	// "All"
	All() string
	// "All Quizzes"
	AllQuizzes() string
	// "Already have an account?"
	AlreadyHaveAnAccount() string
	// "An error occurred"
	AnErrorOccurred() string
	// "Analytics"
	Analytics() string
	// "Answer:"
	Answer() string
	// "Answer Details"
	AnswerDetails() string
	// "Answer Options"
	AnswerOptions() string
	// "Archived"
	Archived() string
	// "Are you sure? This action is reversible."
	AreYouSureThisActionIsReversible() string
	// "Assigned"
	Assigned() string
	// "Attempts"
	Attempts() string
	// "Available"
	Available() string
	// "Available Quizzes"
	AvailableQuizzes() string
	// "Average Score"
	AverageScore() string
	// "Avg Score"
	AvgScore() string
	// "Back"
	Back() string
	// "Back to %s"
	BackTo(param1 string) string
	// "Back to Home"
	BackToHome() string
	// "Back to Quizzes"
	BackToQuizzes() string
	// "Cancel"
	Cancel() string
	// "Check Results"
	CheckResults() string
	// "Chemistry: Organic and inorganic"
	ChemistryOrganicAndInorganic() string
	// "Choice"
	Choice() string
	// "Class"
	Class() string
	// "Compete with classmates. Weekly ratings and bonus rewards!"
	CompeteWithClassmatesWeeklyRatingsAndBonusRewards() string
	// "Completed"
	Completed() string
	// "Control Panel"
	ControlPanel() string
	// "Copyright 2026 GoQuizVibe"
	Copyright2026Goquizvibe() string
	// "Correct"
	Correct() string
	// "Correct Answer"
	CorrectAnswer() string
	// "Create"
	Create() string
	// "Create first quiz"
	CreateFirstQuiz() string
	// "Create Quiz"
	CreateQuiz() string
	// "Danger Zone"
	DangerZone() string
	// "Dashboard"
	Dashboard() string
	// "Date"
	Date() string
	// "day streak"
	DayStreak() string
	// "Delete image?"
	DeleteImage() string
	// "Delete question?"
	DeleteQuestion() string
	// "Delete quiz?"
	DeleteQuiz() string
	// "Description"
	Description() string
	// "Edit"
	Edit() string
	// "Editing: %s"
	Editing(param1 string) string
	// "Email"
	Email() string
	// "Enter your answer..."
	EnterYourAnswer() string
	// "Error"
	Error() string
	// "Excellent"
	Excellent() string
	// "experience points"
	ExperiencePoints() string
	// "Explanation:"
	Explanation() string
	// "Fill"
	Fill() string
	// "Filter by Quiz"
	FilterByQuiz() string
	// "For Students"
	ForStudents() string
	// "Good"
	Good() string
	// "GoQuizVibe Admin"
	GoquizvibeAdmin() string
	// "grade"
	Grade() string
	// "Great job!"
	GreatJob() string
	// "Images (up to 3)"
	ImagesUpTo3() string
	// "Interactive exam preparation platform with gamification. Earn XP, maintain streaks, and compete with friends!"
	InteractiveExamPreparationPlatformWithGamificationEarnXpMaintainStreaksAndCompeteWithFriends() string
	// "Join thousands of students who are already learning with joy!"
	JoinThousandsOfStudentsWhoAreAlreadyLearningWithJoy() string
	// "JPG, PNG, WebP up to 5MB each"
	JpgPngWebpUpTo5mbEach() string
	// "Leaderboard"
	Leaderboard() string
	// "Leaders"
	Leaders() string
	// "Learn Through Play"
	LearnThroughPlay() string
	// "Loading..."
	Loading() string
	// "Log In"
	LogIn() string
	// "made"
	Made() string
	// "Math: From basic arithmetic to algebra"
	MathFromBasicArithmeticToAlgebra() string
	// "min"
	Min() string
	// "Minimum 6 characters"
	Minimum6Characters() string
	// "Mistake"
	Mistake() string
	// "Mistake Review"
	MistakeReview() string
	// "Mistakes"
	Mistakes() string
	// "Mistakes Made"
	MistakesMade() string
	// "Move to Archive"
	MoveToArchive() string
	// "Name"
	Name() string
	// "New Question"
	NewQuestion() string
	// "New quiz with questions"
	NewQuizWithQuestions() string
	// "No account?"
	NoAccount() string
	// "No activity yet"
	NoActivityYet() string
	// "No data yet"
	NoDataYet() string
	// "No participants yet"
	NoParticipantsYet() string
	// "No questions yet"
	NoQuestionsYet() string
	// "No quizzes available yet"
	NoQuizzesAvailableYet() string
	// "No results yet"
	NoResultsYet() string
	// "Open"
	Open() string
	// "Options:"
	Options() string
	// "Overview"
	Overview() string
	// "Page Not Found"
	PageNotFound() string
	// "Password"
	Password() string
	// "Physics: Mechanics, electricity, optics"
	PhysicsMechanicsElectricityOptics() string
	// "Points"
	Points() string
	// "Practice daily to keep your streak. Consistency is the key to success!"
	PracticeDailyToKeepYourStreakConsistencyIsTheKeyToSuccess() string
	// "Question %d"
	Question(param1 int) string
	// "Question %d of %d"
	QuestionOf(param1 int, param2 int) string
	// "Question Text"
	QuestionText() string
	// "Questions (%d)"
	Questions(param1 int) string
	// "Quick Actions"
	QuickActions() string
	// "Quiz"
	Quiz() string
	// "Quiz Completed!"
	QuizCompleted() string
	// "Quiz Information"
	QuizInformation() string
	// "Quiz Management"
	QuizManagement() string
	// "Quiz Results"
	QuizResults() string
	// "Quiz saved"
	QuizSaved() string
	// "Quiz statistics"
	QuizStatistics() string
	// "Quizzes"
	Quizzes() string
	// "Quizzes Completed"
	QuizzesCompleted() string
	// "Ready to Start?"
	ReadyToStart() string
	// "Recent Activity"
	RecentActivity() string
	// "Registration"
	Registration() string
	// "Result"
	Result() string
	// "Results"
	Results() string
	// "Results will appear after students complete quizzes"
	ResultsWillAppearAfterStudentsCompleteQuizzes() string
	// "Retry"
	Retry() string
	// "Satisfactory"
	Satisfactory() string
	// "Save"
	Save() string
	// "Save All"
	SaveAll() string
	// "Save error"
	SaveError() string
	// "See correct answers immediately after each question. Learn from your mistakes!"
	SeeCorrectAnswersImmediatelyAfterEachQuestionLearnFromYourMistakes() string
	// "Sign In"
	SignIn() string
	// "Sign In to Account"
	SignInToAccount() string
	// "Sign Up"
	SignUp() string
	// "Sign Up Free"
	SignUpFree() string
	// "Sorry, the requested page does not exist or has been moved."
	SorryTheRequestedPageDoesNotExistOrHasBeenMoved() string
	// "Start"
	Start() string
	// "Start Free"
	StartFree() string
	// "Statistics"
	Statistics() string
	// "Status"
	Status() string
	// "Streak days in a row"
	StreakDaysInARow() string
	// "Student"
	Student() string
	// "Students by Grade"
	StudentsByGrade() string
	// "Subject"
	Subject() string
	// "Subjects"
	Subjects() string
	// "Submit"
	Submit() string
	// "Success Rate"
	SuccessRate() string
	// "Summary Statistics"
	SummaryStatistics() string
	// "Time"
	Time() string
	// "Time (min)"
	TimeMin() string
	// "Title"
	Title() string
	// "To quiz list"
	ToQuizList() string
	// "Total Attempts"
	TotalAttempts() string
	// "Total Points"
	TotalPoints() string
	// "Total Quizzes"
	TotalQuizzes() string
	// "Total Students"
	TotalStudents() string
	// "Total XP"
	TotalXp() string
	// "Try Again"
	TryAgain() string
	// "Type"
	Type() string
	// "Unsatisfactory"
	Unsatisfactory() string
	// "Upload"
	Upload() string
	// "View student answers"
	ViewStudentAnswers() string
	// "Why GoQuizVibe?"
	WhyGoquizvibe() string
	// "You have no mistakes yet. Keep it up!"
	YouHaveNoMistakesYetKeepItUp() string
	// "Your answer:"
	YourAnswer() string
}

type translator struct {
	locale *gotext.Locale
}

func New(locale Locale) (Translator, error) {
	_, file, _, _ := runtime.Caller(0)
	localesDir := filepath.Dir(file)
	l := gotext.NewLocale(localesDir, string(locale))
	l.AddDomain("default")
	return &translator{locale: l}, nil
}

func (t *translator) Actions() string {
	return t.locale.Get("Actions")
}

func (t *translator) Add() string {
	return t.locale.Get("Add")
}

func (t *translator) AddOption() string {
	return t.locale.Get("Add Option")
}

func (t *translator) AddQuestion() string {
	return t.locale.Get("Add Question")
}

func (t *translator) Admin() string {
	return t.locale.Get("Admin")
}

func (t *translator) All() string {
	return t.locale.Get("All")
}

func (t *translator) AllQuizzes() string {
	return t.locale.Get("All Quizzes")
}

func (t *translator) AlreadyHaveAnAccount() string {
	return t.locale.Get("Already have an account?")
}

func (t *translator) AnErrorOccurred() string {
	return t.locale.Get("An error occurred")
}

func (t *translator) Analytics() string {
	return t.locale.Get("Analytics")
}

func (t *translator) Answer() string {
	return t.locale.Get("Answer:")
}

func (t *translator) AnswerDetails() string {
	return t.locale.Get("Answer Details")
}

func (t *translator) AnswerOptions() string {
	return t.locale.Get("Answer Options")
}

func (t *translator) Archived() string {
	return t.locale.Get("Archived")
}

func (t *translator) AreYouSureThisActionIsReversible() string {
	return t.locale.Get("Are you sure? This action is reversible.")
}

func (t *translator) Assigned() string {
	return t.locale.Get("Assigned")
}

func (t *translator) Attempts() string {
	return t.locale.Get("Attempts")
}

func (t *translator) Available() string {
	return t.locale.Get("Available")
}

func (t *translator) AvailableQuizzes() string {
	return t.locale.Get("Available Quizzes")
}

func (t *translator) AverageScore() string {
	return t.locale.Get("Average Score")
}

func (t *translator) AvgScore() string {
	return t.locale.Get("Avg Score")
}

func (t *translator) Back() string {
	return t.locale.Get("Back")
}

func (t *translator) BackTo(param1 string) string {
	return t.locale.Get("Back to %s", param1)
}

func (t *translator) BackToHome() string {
	return t.locale.Get("Back to Home")
}

func (t *translator) BackToQuizzes() string {
	return t.locale.Get("Back to Quizzes")
}

func (t *translator) Cancel() string {
	return t.locale.Get("Cancel")
}

func (t *translator) CheckResults() string {
	return t.locale.Get("Check Results")
}

func (t *translator) ChemistryOrganicAndInorganic() string {
	return t.locale.Get("Chemistry: Organic and inorganic")
}

func (t *translator) Choice() string {
	return t.locale.Get("Choice")
}

func (t *translator) Class() string {
	return t.locale.Get("Class")
}

func (t *translator) CompeteWithClassmatesWeeklyRatingsAndBonusRewards() string {
	return t.locale.Get("Compete with classmates. Weekly ratings and bonus rewards!")
}

func (t *translator) Completed() string {
	return t.locale.Get("Completed")
}

func (t *translator) ControlPanel() string {
	return t.locale.Get("Control Panel")
}

func (t *translator) Copyright2026Goquizvibe() string {
	return t.locale.Get("Copyright 2026 GoQuizVibe")
}

func (t *translator) Correct() string {
	return t.locale.Get("Correct")
}

func (t *translator) CorrectAnswer() string {
	return t.locale.Get("Correct Answer")
}

func (t *translator) Create() string {
	return t.locale.Get("Create")
}

func (t *translator) CreateFirstQuiz() string {
	return t.locale.Get("Create first quiz")
}

func (t *translator) CreateQuiz() string {
	return t.locale.Get("Create Quiz")
}

func (t *translator) DangerZone() string {
	return t.locale.Get("Danger Zone")
}

func (t *translator) Dashboard() string {
	return t.locale.Get("Dashboard")
}

func (t *translator) Date() string {
	return t.locale.Get("Date")
}

func (t *translator) DayStreak() string {
	return t.locale.Get("day streak")
}

func (t *translator) DeleteImage() string {
	return t.locale.Get("Delete image?")
}

func (t *translator) DeleteQuestion() string {
	return t.locale.Get("Delete question?")
}

func (t *translator) DeleteQuiz() string {
	return t.locale.Get("Delete quiz?")
}

func (t *translator) Description() string {
	return t.locale.Get("Description")
}

func (t *translator) Edit() string {
	return t.locale.Get("Edit")
}

func (t *translator) Editing(param1 string) string {
	return t.locale.Get("Editing: %s", param1)
}

func (t *translator) Email() string {
	return t.locale.Get("Email")
}

func (t *translator) EnterYourAnswer() string {
	return t.locale.Get("Enter your answer...")
}

func (t *translator) Error() string {
	return t.locale.Get("Error")
}

func (t *translator) Excellent() string {
	return t.locale.Get("Excellent")
}

func (t *translator) ExperiencePoints() string {
	return t.locale.Get("experience points")
}

func (t *translator) Explanation() string {
	return t.locale.Get("Explanation:")
}

func (t *translator) Fill() string {
	return t.locale.Get("Fill")
}

func (t *translator) FilterByQuiz() string {
	return t.locale.Get("Filter by Quiz")
}

func (t *translator) ForStudents() string {
	return t.locale.Get("For Students")
}

func (t *translator) Good() string {
	return t.locale.Get("Good")
}

func (t *translator) GoquizvibeAdmin() string {
	return t.locale.Get("GoQuizVibe Admin")
}

func (t *translator) Grade() string {
	return t.locale.Get("grade")
}

func (t *translator) GreatJob() string {
	return t.locale.Get("Great job!")
}

func (t *translator) ImagesUpTo3() string {
	return t.locale.Get("Images (up to 3)")
}

func (t *translator) InteractiveExamPreparationPlatformWithGamificationEarnXpMaintainStreaksAndCompeteWithFriends() string {
	return t.locale.Get("Interactive exam preparation platform with gamification. Earn XP, maintain streaks, and compete with friends!")
}

func (t *translator) JoinThousandsOfStudentsWhoAreAlreadyLearningWithJoy() string {
	return t.locale.Get("Join thousands of students who are already learning with joy!")
}

func (t *translator) JpgPngWebpUpTo5mbEach() string {
	return t.locale.Get("JPG, PNG, WebP up to 5MB each")
}

func (t *translator) Leaderboard() string {
	return t.locale.Get("Leaderboard")
}

func (t *translator) Leaders() string {
	return t.locale.Get("Leaders")
}

func (t *translator) LearnThroughPlay() string {
	return t.locale.Get("Learn Through Play")
}

func (t *translator) Loading() string {
	return t.locale.Get("Loading...")
}

func (t *translator) LogIn() string {
	return t.locale.Get("Log In")
}

func (t *translator) Made() string {
	return t.locale.Get("made")
}

func (t *translator) MathFromBasicArithmeticToAlgebra() string {
	return t.locale.Get("Math: From basic arithmetic to algebra")
}

func (t *translator) Min() string {
	return t.locale.Get("min")
}

func (t *translator) Minimum6Characters() string {
	return t.locale.Get("Minimum 6 characters")
}

func (t *translator) Mistake() string {
	return t.locale.Get("Mistake")
}

func (t *translator) MistakeReview() string {
	return t.locale.Get("Mistake Review")
}

func (t *translator) Mistakes() string {
	return t.locale.Get("Mistakes")
}

func (t *translator) MistakesMade() string {
	return t.locale.Get("Mistakes Made")
}

func (t *translator) MoveToArchive() string {
	return t.locale.Get("Move to Archive")
}

func (t *translator) Name() string {
	return t.locale.Get("Name")
}

func (t *translator) NewQuestion() string {
	return t.locale.Get("New Question")
}

func (t *translator) NewQuizWithQuestions() string {
	return t.locale.Get("New quiz with questions")
}

func (t *translator) NoAccount() string {
	return t.locale.Get("No account?")
}

func (t *translator) NoActivityYet() string {
	return t.locale.Get("No activity yet")
}

func (t *translator) NoDataYet() string {
	return t.locale.Get("No data yet")
}

func (t *translator) NoParticipantsYet() string {
	return t.locale.Get("No participants yet")
}

func (t *translator) NoQuestionsYet() string {
	return t.locale.Get("No questions yet")
}

func (t *translator) NoQuizzesAvailableYet() string {
	return t.locale.Get("No quizzes available yet")
}

func (t *translator) NoResultsYet() string {
	return t.locale.Get("No results yet")
}

func (t *translator) Open() string {
	return t.locale.Get("Open")
}

func (t *translator) Options() string {
	return t.locale.Get("Options:")
}

func (t *translator) Overview() string {
	return t.locale.Get("Overview")
}

func (t *translator) PageNotFound() string {
	return t.locale.Get("Page Not Found")
}

func (t *translator) Password() string {
	return t.locale.Get("Password")
}

func (t *translator) PhysicsMechanicsElectricityOptics() string {
	return t.locale.Get("Physics: Mechanics, electricity, optics")
}

func (t *translator) Points() string {
	return t.locale.Get("Points")
}

func (t *translator) PracticeDailyToKeepYourStreakConsistencyIsTheKeyToSuccess() string {
	return t.locale.Get("Practice daily to keep your streak. Consistency is the key to success!")
}

func (t *translator) Question(param1 int) string {
	return t.locale.Get("Question %d", param1)
}

func (t *translator) QuestionOf(param1 int, param2 int) string {
	return t.locale.Get("Question %d of %d", param1, param2)
}

func (t *translator) QuestionText() string {
	return t.locale.Get("Question Text")
}

func (t *translator) Questions(param1 int) string {
	return t.locale.Get("Questions (%d)", param1)
}

func (t *translator) QuickActions() string {
	return t.locale.Get("Quick Actions")
}

func (t *translator) Quiz() string {
	return t.locale.Get("Quiz")
}

func (t *translator) QuizCompleted() string {
	return t.locale.Get("Quiz Completed!")
}

func (t *translator) QuizInformation() string {
	return t.locale.Get("Quiz Information")
}

func (t *translator) QuizManagement() string {
	return t.locale.Get("Quiz Management")
}

func (t *translator) QuizResults() string {
	return t.locale.Get("Quiz Results")
}

func (t *translator) QuizSaved() string {
	return t.locale.Get("Quiz saved")
}

func (t *translator) QuizStatistics() string {
	return t.locale.Get("Quiz statistics")
}

func (t *translator) Quizzes() string {
	return t.locale.Get("Quizzes")
}

func (t *translator) QuizzesCompleted() string {
	return t.locale.Get("Quizzes Completed")
}

func (t *translator) ReadyToStart() string {
	return t.locale.Get("Ready to Start?")
}

func (t *translator) RecentActivity() string {
	return t.locale.Get("Recent Activity")
}

func (t *translator) Registration() string {
	return t.locale.Get("Registration")
}

func (t *translator) Result() string {
	return t.locale.Get("Result")
}

func (t *translator) Results() string {
	return t.locale.Get("Results")
}

func (t *translator) ResultsWillAppearAfterStudentsCompleteQuizzes() string {
	return t.locale.Get("Results will appear after students complete quizzes")
}

func (t *translator) Retry() string {
	return t.locale.Get("Retry")
}

func (t *translator) Satisfactory() string {
	return t.locale.Get("Satisfactory")
}

func (t *translator) Save() string {
	return t.locale.Get("Save")
}

func (t *translator) SaveAll() string {
	return t.locale.Get("Save All")
}

func (t *translator) SaveError() string {
	return t.locale.Get("Save error")
}

func (t *translator) SeeCorrectAnswersImmediatelyAfterEachQuestionLearnFromYourMistakes() string {
	return t.locale.Get("See correct answers immediately after each question. Learn from your mistakes!")
}

func (t *translator) SignIn() string {
	return t.locale.Get("Sign In")
}

func (t *translator) SignInToAccount() string {
	return t.locale.Get("Sign In to Account")
}

func (t *translator) SignUp() string {
	return t.locale.Get("Sign Up")
}

func (t *translator) SignUpFree() string {
	return t.locale.Get("Sign Up Free")
}

func (t *translator) SorryTheRequestedPageDoesNotExistOrHasBeenMoved() string {
	return t.locale.Get("Sorry, the requested page does not exist or has been moved.")
}

func (t *translator) Start() string {
	return t.locale.Get("Start")
}

func (t *translator) StartFree() string {
	return t.locale.Get("Start Free")
}

func (t *translator) Statistics() string {
	return t.locale.Get("Statistics")
}

func (t *translator) Status() string {
	return t.locale.Get("Status")
}

func (t *translator) StreakDaysInARow() string {
	return t.locale.Get("Streak days in a row")
}

func (t *translator) Student() string {
	return t.locale.Get("Student")
}

func (t *translator) StudentsByGrade() string {
	return t.locale.Get("Students by Grade")
}

func (t *translator) Subject() string {
	return t.locale.Get("Subject")
}

func (t *translator) Subjects() string {
	return t.locale.Get("Subjects")
}

func (t *translator) Submit() string {
	return t.locale.Get("Submit")
}

func (t *translator) SuccessRate() string {
	return t.locale.Get("Success Rate")
}

func (t *translator) SummaryStatistics() string {
	return t.locale.Get("Summary Statistics")
}

func (t *translator) Time() string {
	return t.locale.Get("Time")
}

func (t *translator) TimeMin() string {
	return t.locale.Get("Time (min)")
}

func (t *translator) Title() string {
	return t.locale.Get("Title")
}

func (t *translator) ToQuizList() string {
	return t.locale.Get("To quiz list")
}

func (t *translator) TotalAttempts() string {
	return t.locale.Get("Total Attempts")
}

func (t *translator) TotalPoints() string {
	return t.locale.Get("Total Points")
}

func (t *translator) TotalQuizzes() string {
	return t.locale.Get("Total Quizzes")
}

func (t *translator) TotalStudents() string {
	return t.locale.Get("Total Students")
}

func (t *translator) TotalXp() string {
	return t.locale.Get("Total XP")
}

func (t *translator) TryAgain() string {
	return t.locale.Get("Try Again")
}

func (t *translator) Type() string {
	return t.locale.Get("Type")
}

func (t *translator) Unsatisfactory() string {
	return t.locale.Get("Unsatisfactory")
}

func (t *translator) Upload() string {
	return t.locale.Get("Upload")
}

func (t *translator) ViewStudentAnswers() string {
	return t.locale.Get("View student answers")
}

func (t *translator) WhyGoquizvibe() string {
	return t.locale.Get("Why GoQuizVibe?")
}

func (t *translator) YouHaveNoMistakesYetKeepItUp() string {
	return t.locale.Get("You have no mistakes yet. Keep it up!")
}

func (t *translator) YourAnswer() string {
	return t.locale.Get("Your answer:")
}
