// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: typst.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TypstCompiler_Compile_FullMethodName = "/typst.TypstCompiler/Compile"
)

// TypstCompilerClient is the client API for TypstCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypstCompilerClient interface {
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type typstCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewTypstCompilerClient(cc grpc.ClientConnInterface) TypstCompilerClient {
	return &typstCompilerClient{cc}
}

func (c *typstCompilerClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, TypstCompiler_Compile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypstCompilerServer is the server API for TypstCompiler service.
// All implementations must embed UnimplementedTypstCompilerServer
// for forward compatibility.
type TypstCompilerServer interface {
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	mustEmbedUnimplementedTypstCompilerServer()
}

// UnimplementedTypstCompilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTypstCompilerServer struct{}

func (UnimplementedTypstCompilerServer) Compile(context.Context, *CompileRequest) (*CompileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedTypstCompilerServer) mustEmbedUnimplementedTypstCompilerServer() {}
func (UnimplementedTypstCompilerServer) testEmbeddedByValue()                       {}

// UnsafeTypstCompilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypstCompilerServer will
// result in compilation errors.
type UnsafeTypstCompilerServer interface {
	mustEmbedUnimplementedTypstCompilerServer()
}

func RegisterTypstCompilerServer(s grpc.ServiceRegistrar, srv TypstCompilerServer) {
	// If the following call panics, it indicates UnimplementedTypstCompilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TypstCompiler_ServiceDesc, srv)
}

func _TypstCompiler_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypstCompilerServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypstCompiler_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypstCompilerServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypstCompiler_ServiceDesc is the grpc.ServiceDesc for TypstCompiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypstCompiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "typst.TypstCompiler",
	HandlerType: (*TypstCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _TypstCompiler_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "typst.proto",
}
