// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning_materials.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLearningMaterial = `-- name: CreateLearningMaterial :one
INSERT INTO learning_materials (id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at
`

type CreateLearningMaterialParams struct {
	ID           uuid.UUID            `json:"id"`
	Title        string               `json:"title"`
	Description  string               `json:"description"`
	MaterialType LearningMaterialType `json:"material_type"`
	OwnerID      uuid.UUID            `json:"owner_id"`
	SourcePath   string               `json:"source_path"`
	CompiledPath string               `json:"compiled_path"`
	ResourcePath string               `json:"resource_path"`
	FileSize     pgtype.Int8          `json:"file_size"`
	MimeType     string               `json:"mime_type"`
	CreatedAt    time.Time            `json:"created_at"`
	UpdatedAt    time.Time            `json:"updated_at"`
}

func (q *Queries) CreateLearningMaterial(ctx context.Context, arg CreateLearningMaterialParams) (LearningMaterial, error) {
	row := q.db.QueryRow(ctx, createLearningMaterial,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.MaterialType,
		arg.OwnerID,
		arg.SourcePath,
		arg.CompiledPath,
		arg.ResourcePath,
		arg.FileSize,
		arg.MimeType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i LearningMaterial
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.MaterialType,
		&i.OwnerID,
		&i.SourcePath,
		&i.CompiledPath,
		&i.ResourcePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLearningMaterial = `-- name: DeleteLearningMaterial :exec
DELETE FROM learning_materials WHERE id = $1
`

func (q *Queries) DeleteLearningMaterial(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLearningMaterial, id)
	return err
}

const getLearningMaterialByID = `-- name: GetLearningMaterialByID :one
SELECT id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at FROM learning_materials WHERE id = $1
`

func (q *Queries) GetLearningMaterialByID(ctx context.Context, id uuid.UUID) (LearningMaterial, error) {
	row := q.db.QueryRow(ctx, getLearningMaterialByID, id)
	var i LearningMaterial
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.MaterialType,
		&i.OwnerID,
		&i.SourcePath,
		&i.CompiledPath,
		&i.ResourcePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLearningMaterials = `-- name: GetLearningMaterials :many
SELECT id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at FROM learning_materials ORDER BY created_at DESC
`

func (q *Queries) GetLearningMaterials(ctx context.Context) ([]LearningMaterial, error) {
	rows, err := q.db.Query(ctx, getLearningMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningMaterial{}
	for rows.Next() {
		var i LearningMaterial
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.MaterialType,
			&i.OwnerID,
			&i.SourcePath,
			&i.CompiledPath,
			&i.ResourcePath,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLearningMaterialsByOwner = `-- name: GetLearningMaterialsByOwner :many
SELECT id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at FROM learning_materials WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetLearningMaterialsByOwner(ctx context.Context, ownerID uuid.UUID) ([]LearningMaterial, error) {
	rows, err := q.db.Query(ctx, getLearningMaterialsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningMaterial{}
	for rows.Next() {
		var i LearningMaterial
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.MaterialType,
			&i.OwnerID,
			&i.SourcePath,
			&i.CompiledPath,
			&i.ResourcePath,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLearningMaterials = `-- name: GetRecentLearningMaterials :many
SELECT id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at FROM learning_materials ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) GetRecentLearningMaterials(ctx context.Context, limit int32) ([]LearningMaterial, error) {
	rows, err := q.db.Query(ctx, getRecentLearningMaterials, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningMaterial{}
	for rows.Next() {
		var i LearningMaterial
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.MaterialType,
			&i.OwnerID,
			&i.SourcePath,
			&i.CompiledPath,
			&i.ResourcePath,
			&i.FileSize,
			&i.MimeType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearningMaterial = `-- name: UpdateLearningMaterial :one
UPDATE learning_materials
SET title = $2, description = $3, source_path = $4, compiled_path = $5, resource_path = $6, file_size = $7, mime_type = $8, updated_at = $9
WHERE id = $1
RETURNING id, title, description, material_type, owner_id, source_path, compiled_path, resource_path, file_size, mime_type, created_at, updated_at
`

type UpdateLearningMaterialParams struct {
	ID           uuid.UUID   `json:"id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	SourcePath   string      `json:"source_path"`
	CompiledPath string      `json:"compiled_path"`
	ResourcePath string      `json:"resource_path"`
	FileSize     pgtype.Int8 `json:"file_size"`
	MimeType     string      `json:"mime_type"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateLearningMaterial(ctx context.Context, arg UpdateLearningMaterialParams) (LearningMaterial, error) {
	row := q.db.QueryRow(ctx, updateLearningMaterial,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SourcePath,
		arg.CompiledPath,
		arg.ResourcePath,
		arg.FileSize,
		arg.MimeType,
		arg.UpdatedAt,
	)
	var i LearningMaterial
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.MaterialType,
		&i.OwnerID,
		&i.SourcePath,
		&i.CompiledPath,
		&i.ResourcePath,
		&i.FileSize,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
