// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO quiz_attempts (id, user_id, quiz_id, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, quiz_id, score, max_score, started_at, completed_at
`

type CreateAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	QuizID    uuid.UUID `json:"quiz_id"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.UserID,
		arg.QuizID,
		arg.StartedAt,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserAnswer = `-- name: CreateUserAnswer :one
INSERT INTO user_answers (id, attempt_id, question_id, user_answer, is_correct)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, attempt_id, question_id, user_answer, is_correct
`

type CreateUserAnswerParams struct {
	ID         uuid.UUID `json:"id"`
	AttemptID  uuid.UUID `json:"attempt_id"`
	QuestionID uuid.UUID `json:"question_id"`
	UserAnswer string    `json:"user_answer"`
	IsCorrect  bool      `json:"is_correct"`
}

func (q *Queries) CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) (UserAnswer, error) {
	row := q.db.QueryRow(ctx, createUserAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.UserAnswer,
		arg.IsCorrect,
	)
	var i UserAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
	)
	return i, err
}

const getAllAttempts = `-- name: GetAllAttempts :many
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at,
       u.name as user_name, q.title as quiz_title
FROM quiz_attempts a
JOIN users u ON u.id = a.user_id
JOIN quizzes q ON q.id = a.quiz_id
WHERE a.completed_at IS NOT NULL
ORDER BY a.completed_at DESC
`

type GetAllAttemptsRow struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	QuizID      uuid.UUID    `json:"quiz_id"`
	Score       int          `json:"score"`
	MaxScore    int          `json:"max_score"`
	StartedAt   time.Time    `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UserName    string       `json:"user_name"`
	QuizTitle   string       `json:"quiz_title"`
}

func (q *Queries) GetAllAttempts(ctx context.Context) ([]GetAllAttemptsRow, error) {
	rows, err := q.db.Query(ctx, getAllAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAttemptsRow{}
	for rows.Next() {
		var i GetAllAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UserName,
			&i.QuizTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswersByAttempt = `-- name: GetAnswersByAttempt :many
SELECT id, attempt_id, question_id, user_answer, is_correct FROM user_answers WHERE attempt_id = $1
`

func (q *Queries) GetAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error) {
	rows, err := q.db.Query(ctx, getAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAnswer{}
	for rows.Next() {
		var i UserAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, user_id, quiz_id, score, max_score, started_at, completed_at FROM quiz_attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAttemptsByQuiz = `-- name: GetAttemptsByQuiz :many
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at,
       u.name as user_name
FROM quiz_attempts a
JOIN users u ON u.id = a.user_id
WHERE a.quiz_id = $1 AND a.completed_at IS NOT NULL
ORDER BY a.completed_at DESC
`

type GetAttemptsByQuizRow struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	QuizID      uuid.UUID    `json:"quiz_id"`
	Score       int          `json:"score"`
	MaxScore    int          `json:"max_score"`
	StartedAt   time.Time    `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UserName    string       `json:"user_name"`
}

func (q *Queries) GetAttemptsByQuiz(ctx context.Context, quizID uuid.UUID) ([]GetAttemptsByQuizRow, error) {
	rows, err := q.db.Query(ctx, getAttemptsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttemptsByQuizRow{}
	for rows.Next() {
		var i GetAttemptsByQuizRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptsByUser = `-- name: GetAttemptsByUser :many
SELECT id, user_id, quiz_id, score, max_score, started_at, completed_at FROM quiz_attempts WHERE user_id = $1 AND completed_at IS NOT NULL ORDER BY started_at DESC
`

func (q *Queries) GetAttemptsByUser(ctx context.Context, userID uuid.UUID) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedAttemptBySessionID = `-- name: GetCompletedAttemptBySessionID :one
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at FROM quiz_attempts a
JOIN quiz_sessions s ON s.attempt_id = a.id
WHERE s.id = $1 AND a.completed_at IS NOT NULL
`

func (q *Queries) GetCompletedAttemptBySessionID(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getCompletedAttemptBySessionID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCompletedAttemptsCount = `-- name: GetCompletedAttemptsCount :one
SELECT COUNT(*) FROM quiz_attempts
WHERE user_id = $1 AND completed_at IS NOT NULL
`

func (q *Queries) GetCompletedAttemptsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCompletedAttemptsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGradeDistribution = `-- name: GetGradeDistribution :one
SELECT json_object_agg(grade_level, count) as grade_dist FROM (
    SELECT COALESCE(grade::text, 'unknown') as grade_level, COUNT(*) as count 
    FROM quizzes WHERE status != 'archived' AND grade IS NOT NULL 
    GROUP BY grade
) sub
`

func (q *Queries) GetGradeDistribution(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGradeDistribution)
	var grade_dist []byte
	err := row.Scan(&grade_dist)
	return grade_dist, err
}

const getLastActiveDate = `-- name: GetLastActiveDate :one
SELECT MAX(completed_at) FROM quiz_attempts
WHERE user_id = $1 AND completed_at IS NOT NULL
`

func (q *Queries) GetLastActiveDate(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLastActiveDate, userID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getQuizErrors = `-- name: GetQuizErrors :many
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at FROM quiz_attempts a
WHERE a.user_id = $1 AND a.completed_at IS NOT NULL
`

func (q *Queries) GetQuizErrors(ctx context.Context, userID uuid.UUID) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, getQuizErrors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizStats = `-- name: GetQuizStats :many
SELECT
    q.id as quiz_id, q.title, q.subject,
    COUNT(a.id) as attempt_count,
    COALESCE(AVG(a.score * 100.0 / NULLIF(a.max_score, 0)), 0) as avg_score,
    CASE WHEN COUNT(a.id) > 0
         THEN (COUNT(*) FILTER (WHERE a.score * 100.0 / NULLIF(a.max_score, 0) >= 60))::float / COUNT(*) * 100
         ELSE 0
    END as pass_rate
FROM quizzes q
LEFT JOIN quiz_attempts a ON a.quiz_id = q.id AND a.completed_at IS NOT NULL AND a.max_score > 0
WHERE q.status != 'archived'
GROUP BY q.id, q.title, q.subject
ORDER BY q.created_at DESC
`

type GetQuizStatsRow struct {
	QuizID       uuid.UUID   `json:"quiz_id"`
	Title        string      `json:"title"`
	Subject      string      `json:"subject"`
	AttemptCount int64       `json:"attempt_count"`
	AvgScore     interface{} `json:"avg_score"`
	PassRate     int32       `json:"pass_rate"`
}

func (q *Queries) GetQuizStats(ctx context.Context) ([]GetQuizStatsRow, error) {
	rows, err := q.db.Query(ctx, getQuizStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuizStatsRow{}
	for rows.Next() {
		var i GetQuizStatsRow
		if err := rows.Scan(
			&i.QuizID,
			&i.Title,
			&i.Subject,
			&i.AttemptCount,
			&i.AvgScore,
			&i.PassRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAttempts = `-- name: GetRecentAttempts :many
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at,
       u.name as user_name, q.title as quiz_title
FROM quiz_attempts a
JOIN users u ON u.id = a.user_id
JOIN quizzes q ON q.id = a.quiz_id
WHERE a.completed_at IS NOT NULL
ORDER BY a.completed_at DESC LIMIT $1
`

type GetRecentAttemptsRow struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	QuizID      uuid.UUID    `json:"quiz_id"`
	Score       int          `json:"score"`
	MaxScore    int          `json:"max_score"`
	StartedAt   time.Time    `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UserName    string       `json:"user_name"`
	QuizTitle   string       `json:"quiz_title"`
}

func (q *Queries) GetRecentAttempts(ctx context.Context, limit int32) ([]GetRecentAttemptsRow, error) {
	rows, err := q.db.Query(ctx, getRecentAttempts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentAttemptsRow{}
	for rows.Next() {
		var i GetRecentAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UserName,
			&i.QuizTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectDistribution = `-- name: GetSubjectDistribution :one
SELECT json_object_agg(subject_name, count) as subject_dist FROM (
    SELECT subject as subject_name, COUNT(*) as count FROM quizzes WHERE status != 'archived' AND subject IS NOT NULL GROUP BY subject
) sub
`

func (q *Queries) GetSubjectDistribution(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSubjectDistribution)
	var subject_dist []byte
	err := row.Scan(&subject_dist)
	return subject_dist, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COALESCE((SELECT SUM(score) FROM quiz_attempts qa WHERE qa.user_id = $1 AND qa.completed_at IS NOT NULL), 0) as total_xp,
    (SELECT COUNT(*) FROM user_answers ua JOIN quiz_attempts a ON a.id = ua.attempt_id WHERE a.user_id = $1 AND a.completed_at IS NOT NULL AND ua.is_correct = true) as correct_cnt,
    (SELECT COUNT(*) FROM user_answers ua JOIN quiz_attempts a ON a.id = ua.attempt_id WHERE a.user_id = $1 AND a.completed_at IS NOT NULL AND ua.is_correct = false) as wrong_cnt
`

type GetUserStatsRow struct {
	TotalXp    interface{} `json:"total_xp"`
	CorrectCnt int64       `json:"correct_cnt"`
	WrongCnt   int64       `json:"wrong_cnt"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalXp, &i.CorrectCnt, &i.WrongCnt)
	return i, err
}

const getWrongAnswersByAttempt = `-- name: GetWrongAnswersByAttempt :many
SELECT ua.id, ua.attempt_id, ua.question_id, ua.user_answer, ua.is_correct FROM user_answers ua
WHERE ua.attempt_id = $1 AND ua.is_correct = false
`

func (q *Queries) GetWrongAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error) {
	rows, err := q.db.Query(ctx, getWrongAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAnswer{}
	for rows.Next() {
		var i UserAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttempt = `-- name: UpdateAttempt :one
UPDATE quiz_attempts SET score = $2, max_score = $3, completed_at = $4
WHERE id = $1
RETURNING id, user_id, quiz_id, score, max_score, started_at, completed_at
`

type UpdateAttemptParams struct {
	ID          uuid.UUID    `json:"id"`
	Score       int          `json:"score"`
	MaxScore    int          `json:"max_score"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, updateAttempt,
		arg.ID,
		arg.Score,
		arg.MaxScore,
		arg.CompletedAt,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
