// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO quiz_attempts (id, user_id, quiz_id, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, quiz_id, score, max_score, started_at, completed_at
`

type CreateAttemptParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	QuizID    uuid.UUID `json:"quiz_id"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.UserID,
		arg.QuizID,
		arg.StartedAt,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createUserAnswer = `-- name: CreateUserAnswer :one
INSERT INTO user_answers (id, attempt_id, question_id, user_answer, is_correct)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, attempt_id, question_id, user_answer, is_correct
`

type CreateUserAnswerParams struct {
	ID         uuid.UUID `json:"id"`
	AttemptID  uuid.UUID `json:"attempt_id"`
	QuestionID uuid.UUID `json:"question_id"`
	UserAnswer string    `json:"user_answer"`
	IsCorrect  bool      `json:"is_correct"`
}

func (q *Queries) CreateUserAnswer(ctx context.Context, arg CreateUserAnswerParams) (UserAnswer, error) {
	row := q.db.QueryRow(ctx, createUserAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.UserAnswer,
		arg.IsCorrect,
	)
	var i UserAnswer
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
	)
	return i, err
}

const getAnswersByAttempt = `-- name: GetAnswersByAttempt :many
SELECT id, attempt_id, question_id, user_answer, is_correct FROM user_answers WHERE attempt_id = $1
`

func (q *Queries) GetAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error) {
	rows, err := q.db.Query(ctx, getAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAnswer{}
	for rows.Next() {
		var i UserAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttemptByID = `-- name: GetAttemptByID :one
SELECT id, user_id, quiz_id, score, max_score, started_at, completed_at FROM quiz_attempts WHERE id = $1
`

func (q *Queries) GetAttemptByID(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getAttemptByID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAttemptsByUser = `-- name: GetAttemptsByUser :many
SELECT id, user_id, quiz_id, score, max_score, started_at, completed_at FROM quiz_attempts WHERE user_id = $1 ORDER BY started_at DESC
`

func (q *Queries) GetAttemptsByUser(ctx context.Context, userID uuid.UUID) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, getAttemptsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedAttemptBySessionID = `-- name: GetCompletedAttemptBySessionID :one
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at FROM quiz_attempts a
JOIN quiz_sessions s ON s.attempt_id = a.id
WHERE s.id = $1 AND a.completed_at IS NOT NULL
`

func (q *Queries) GetCompletedAttemptBySessionID(ctx context.Context, id uuid.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getCompletedAttemptBySessionID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCompletedAttemptsCount = `-- name: GetCompletedAttemptsCount :one
SELECT COUNT(*) FROM quiz_attempts
WHERE user_id = $1 AND completed_at IS NOT NULL
`

func (q *Queries) GetCompletedAttemptsCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCompletedAttemptsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastActiveDate = `-- name: GetLastActiveDate :one
SELECT MAX(completed_at) FROM quiz_attempts
WHERE user_id = $1 AND completed_at IS NOT NULL
`

func (q *Queries) GetLastActiveDate(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLastActiveDate, userID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const getQuizErrors = `-- name: GetQuizErrors :many
SELECT a.id, a.user_id, a.quiz_id, a.score, a.max_score, a.started_at, a.completed_at FROM quiz_attempts a
WHERE a.user_id = $1 AND a.completed_at IS NOT NULL
`

func (q *Queries) GetQuizErrors(ctx context.Context, userID uuid.UUID) ([]QuizAttempt, error) {
	rows, err := q.db.Query(ctx, getQuizErrors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizAttempt{}
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizID,
			&i.Score,
			&i.MaxScore,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COALESCE(SUM(q.points), 0) as total_xp,
    COUNT(CASE WHEN ua.is_correct = true THEN 1 END) as correct_cnt,
    COUNT(CASE WHEN ua.is_correct = false THEN 1 END) as wrong_cnt
FROM user_answers ua
JOIN questions q ON q.id = ua.question_id
JOIN quiz_attempts a ON a.id = ua.attempt_id
WHERE a.user_id = $1
`

type GetUserStatsRow struct {
	TotalXp    interface{} `json:"total_xp"`
	CorrectCnt int64       `json:"correct_cnt"`
	WrongCnt   int64       `json:"wrong_cnt"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalXp, &i.CorrectCnt, &i.WrongCnt)
	return i, err
}

const getWrongAnswersByAttempt = `-- name: GetWrongAnswersByAttempt :many
SELECT ua.id, ua.attempt_id, ua.question_id, ua.user_answer, ua.is_correct FROM user_answers ua
WHERE ua.attempt_id = $1 AND ua.is_correct = false
`

func (q *Queries) GetWrongAnswersByAttempt(ctx context.Context, attemptID uuid.UUID) ([]UserAnswer, error) {
	rows, err := q.db.Query(ctx, getWrongAnswersByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAnswer{}
	for rows.Next() {
		var i UserAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttempt = `-- name: UpdateAttempt :one
UPDATE quiz_attempts SET score = $2, max_score = $3, completed_at = $4
WHERE id = $1
RETURNING id, user_id, quiz_id, score, max_score, started_at, completed_at
`

type UpdateAttemptParams struct {
	ID          uuid.UUID `json:"id"`
	Score       int       `json:"score"`
	MaxScore    int       `json:"max_score"`
	CompletedAt time.Time `json:"completed_at"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, updateAttempt,
		arg.ID,
		arg.Score,
		arg.MaxScore,
		arg.CompletedAt,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.Score,
		&i.MaxScore,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
