// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO quiz_sessions (id, user_id, quiz_id, attempt_id, current_index, answers, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, quiz_id, attempt_id, current_index, answers, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	QuizID       uuid.UUID `json:"quiz_id"`
	AttemptID    uuid.UUID `json:"attempt_id"`
	CurrentIndex int       `json:"current_index"`
	Answers      []byte    `json:"answers"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (QuizSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.QuizID,
		arg.AttemptID,
		arg.CurrentIndex,
		arg.Answers,
		arg.CreatedAt,
	)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.AttemptID,
		&i.CurrentIndex,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM quiz_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, quiz_id, attempt_id, current_index, answers, created_at FROM quiz_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (QuizSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.AttemptID,
		&i.CurrentIndex,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByAttemptID = `-- name: GetSessionByAttemptID :one
SELECT id, user_id, quiz_id, attempt_id, current_index, answers, created_at FROM quiz_sessions WHERE attempt_id = $1
`

func (q *Queries) GetSessionByAttemptID(ctx context.Context, attemptID uuid.UUID) (QuizSession, error) {
	row := q.db.QueryRow(ctx, getSessionByAttemptID, attemptID)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.AttemptID,
		&i.CurrentIndex,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE quiz_sessions SET current_index = $2, answers = $3
WHERE id = $1
RETURNING id, user_id, quiz_id, attempt_id, current_index, answers, created_at
`

type UpdateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	CurrentIndex int       `json:"current_index"`
	Answers      []byte    `json:"answers"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (QuizSession, error) {
	row := q.db.QueryRow(ctx, updateSession, arg.ID, arg.CurrentIndex, arg.Answers)
	var i QuizSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizID,
		&i.AttemptID,
		&i.CurrentIndex,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

func (q *Queries) SessionExists(ctx context.Context, id uuid.UUID) (bool, error) {
	var exists bool
	err := q.db.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM quiz_sessions WHERE id = $1)`, id).Scan(&exists)
	return exists, err
}
