// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package editor

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EditorPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Typst Editor</title><link href=\"/static/style/editor.css\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"></head><body><div class=\"editor-container\"><aside id=\"files-panel\" class=\"files-panel\"><div class=\"files-header\"><span>Files</span> <button id=\"toggle-files\" class=\"btn-toggle\" title=\"Toggle files panel\"><i class=\"fas fa-chevron-left\"></i></button></div><div id=\"file-actions\" class=\"file-actions\"><button id=\"new-file\" class=\"btn-action\" title=\"New file\"><i class=\"fas fa-plus\"></i></button> <button id=\"delete-file\" class=\"btn-action\" title=\"Delete file\" disabled><i class=\"fas fa-trash\"></i></button></div><div id=\"file-list\" class=\"file-list\"></div></aside><div class=\"resize-handler-v\" data-resize=\"files\"></div><div class=\"main-area\"><div class=\"editor-panel\"><div id=\"editor-container\"></div></div><div class=\"resize-handler-h\" data-resize=\"editor-preview\"></div><div class=\"preview-panel\"><div id=\"preview-container\"></div></div><div class=\"errors-panel\"><div class=\"errors-header\"><i class=\"fas fa-exclamation-circle\"></i> <span>Errors</span></div><div id=\"errors-list\" class=\"errors-list\"></div></div></div></div><script src=\"/static/scripts/typst/typst.bundle.js\" type=\"module\"></script><script src=\"/static/scripts/editor/editor.bundle.js\" type=\"module\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
