// Code generated by gettextcodegen. DO NOT EDIT.

package locales

import (
	"path/filepath"
	"runtime"

	"github.com/leonelquinteros/gotext"
)

type Locale string

const (
	LocaleInvalid Locale = ""
	LocaleEn Locale = "en"
	LocaleRu Locale = "ru"
)

type Translator interface {
	// "Access"
	Access() string
	// "Actions"
	Actions() string
	// "Add"
	Add() string
	// "Add Member"
	AddMember() string
	// "Add Option"
	AddOption() string
	// "Add Question"
	AddQuestion() string
	// "Admin"
	Admin() string
	// "Admins"
	Admins() string
	// "All"
	All() string
	// "All Questions Answered! End quiz?"
	AllQuestionsAnsweredEndQuiz() string
	// "All Quizzes"
	AllQuizzes() string
	// "Already have an account?"
	AlreadyHaveAnAccount() string
	// "An error occurred"
	AnErrorOccurred() string
	// "Analytics"
	Analytics() string
	// "Another test"
	AnotherTest() string
	// "Answer:"
	Answer() string
	// "Answer Details"
	AnswerDetails() string
	// "Answer Options"
	AnswerOptions() string
	// "Archived"
	Archived() string
	// "Are you sure? This action is reversible."
	AreYouSureThisActionIsReversible() string
	// "Are you sure you want to delete this material?"
	AreYouSureYouWantToDeleteThisMaterial() string
	// "Assigned"
	Assigned() string
	// "Attempts"
	Attempts() string
	// "Available"
	Available() string
	// "Available Quizzes"
	AvailableQuizzes() string
	// "Average Score"
	AverageScore() string
	// "Avg Score"
	AvgScore() string
	// "Back"
	Back() string
	// "Back to %s"
	BackTo(param1 string) string
	// "Back to Edit"
	BackToEdit() string
	// "Back to Home"
	BackToHome() string
	// "Back to List"
	BackToList() string
	// "Back to Quizzes"
	BackToQuizzes() string
	// "Can Edit"
	CanEdit() string
	// "Can View"
	CanView() string
	// "Cancel"
	Cancel() string
	// "Cancel and start new"
	CancelAndStartNew() string
	// "Cancelling will complete the current test with your current answers. This action cannot be undone."
	CancellingWillCompleteTheCurrentTestWithYourCurrentAnswersThisActionCannotBeUndone() string
	// "Check Results"
	CheckResults() string
	// "Chemistry: Organic and inorganic"
	ChemistryOrganicAndInorganic() string
	// "Choice"
	Choice() string
	// "Class"
	Class() string
	// "Compete with classmates. Weekly ratings and bonus rewards!"
	CompeteWithClassmatesWeeklyRatingsAndBonusRewards() string
	// "Completed"
	Completed() string
	// "Control Panel"
	ControlPanel() string
	// "Copyright 2026 GoQuizVibe"
	Copyright2026Goquizvibe() string
	// "Correct"
	Correct() string
	// "Correct Answer"
	CorrectAnswer() string
	// "correct_answer (string) - correct answer"
	CorrectAnswerStringCorrectAnswer() string
	// "Create"
	Create() string
	// "Create First Learning Material"
	CreateFirstLearningMaterial() string
	// "Create first quiz"
	CreateFirstQuiz() string
	// "Create from Template"
	CreateFromTemplate() string
	// "Create Group"
	CreateGroup() string
	// "Create Learning Material"
	CreateLearningMaterial() string
	// "Create Quiz"
	CreateQuiz() string
	// "Created At"
	CreatedAt() string
	// "Danger Zone"
	DangerZone() string
	// "Dashboard"
	Dashboard() string
	// "Date"
	Date() string
	// "day streak"
	DayStreak() string
	// "Delete"
	Delete() string
	// "Delete Group"
	DeleteGroup() string
	// "Delete image?"
	DeleteImage() string
	// "Delete question?"
	DeleteQuestion() string
	// "Delete quiz?"
	DeleteQuiz() string
	// "Description"
	Description() string
	// "Download Prompt as File"
	DownloadPromptAsFile() string
	// "Each question must contain the following fields:"
	EachQuestionMustContainTheFollowingFields() string
	// "Edit"
	Edit() string
	// "Editing: %s"
	Editing(param1 string) string
	// "Email"
	Email() string
	// "End quiz? This action cannot be undone."
	EndQuizThisActionCannotBeUndone() string
	// "Enter quiz topic above to generate prompt"
	EnterQuizTopicAboveToGeneratePrompt() string
	// "Enter your answer..."
	EnterYourAnswer() string
	// "Error"
	Error() string
	// "Excellent"
	Excellent() string
	// "experience points"
	ExperiencePoints() string
	// "Explanation:"
	Explanation() string
	// "explanation (string) - explanation for the answer"
	ExplanationStringExplanationForTheAnswer() string
	// "Failed to import questions"
	FailedToImportQuestions() string
	// "File Size"
	FileSize() string
	// "Fill"
	Fill() string
	// "Filter by Quiz"
	FilterByQuiz() string
	// "For Students"
	ForStudents() string
	// "Good"
	Good() string
	// "GoQuizVibe Admin"
	GoquizvibeAdmin() string
	// "grade"
	Grade() string
	// "Grant Access"
	GrantAccess() string
	// "Great job!"
	GreatJob() string
	// "Group"
	Group() string
	// "Group created"
	GroupCreated() string
	// "Group deleted"
	GroupDeleted() string
	// "Group Name"
	GroupName() string
	// "Group updated"
	GroupUpdated() string
	// "Images (up to 3)"
	ImagesUpTo3() string
	// "Import"
	Import() string
	// "Import from JSON"
	ImportFromJson() string
	// "Import Questions"
	ImportQuestions() string
	// "Interactive exam preparation platform with gamification. Earn XP, maintain streaks, and compete with friends!"
	InteractiveExamPreparationPlatformWithGamificationEarnXpMaintainStreaksAndCompeteWithFriends() string
	// "Invalid JSON format"
	InvalidJsonFormat() string
	// "Join thousands of students who are already learning with joy!"
	JoinThousandsOfStudentsWhoAreAlreadyLearningWithJoy() string
	// "JPG, PNG, WebP up to 5MB each"
	JpgPngWebpUpTo5mbEach() string
	// "JSON Schema for question object"
	JsonSchemaForQuestionObject() string
	// "JSON structure for question:"
	JsonStructureForQuestion() string
	// "Language"
	Language() string
	// "Leaderboard"
	Leaderboard() string
	// "Leaders"
	Leaders() string
	// "Learn Through Play"
	LearnThroughPlay() string
	// "Learning Material Description Placeholder"
	LearningMaterialDescriptionPlaceholder() string
	// "Learning Material Title Placeholder"
	LearningMaterialTitlePlaceholder() string
	// "Learning Materials"
	LearningMaterials() string
	// "Leave Group"
	LeaveGroup() string
	// "Left group"
	LeftGroup() string
	// "Loading..."
	Loading() string
	// "Log In"
	LogIn() string
	// "made"
	Made() string
	// "Make Admin"
	MakeAdmin() string
	// "Material Type"
	MaterialType() string
	// "Math: From basic arithmetic to algebra"
	MathFromBasicArithmeticToAlgebra() string
	// "Member"
	Member() string
	// "Member added"
	MemberAdded() string
	// "Member removed"
	MemberRemoved() string
	// "Members"
	Members() string
	// "Mime Type"
	MimeType() string
	// "min"
	Min() string
	// "Minimum 6 characters"
	Minimum6Characters() string
	// "Mistake"
	Mistake() string
	// "Mistake Review"
	MistakeReview() string
	// "Mistakes"
	Mistakes() string
	// "Mistakes Made"
	MistakesMade() string
	// "Move to Archive"
	MoveToArchive() string
	// "My Groups"
	MyGroups() string
	// "Name"
	Name() string
	// "New Question"
	NewQuestion() string
	// "New quiz with questions"
	NewQuizWithQuestions() string
	// "No access"
	NoAccess() string
	// "No account?"
	NoAccount() string
	// "No activity yet"
	NoActivityYet() string
	// "No data yet"
	NoDataYet() string
	// "No groups yet"
	NoGroupsYet() string
	// "No Learning Materials Available"
	NoLearningMaterialsAvailable() string
	// "No Materials Yet"
	NoMaterialsYet() string
	// "No participants yet"
	NoParticipantsYet() string
	// "No permissions yet"
	NoPermissionsYet() string
	// "No Preview Available"
	NoPreviewAvailable() string
	// "No questions yet"
	NoQuestionsYet() string
	// "No quizzes available yet"
	NoQuizzesAvailableYet() string
	// "No results yet"
	NoResultsYet() string
	// "Open"
	Open() string
	// "Open in New Tab"
	OpenInNewTab() string
	// "Open Resource"
	OpenResource() string
	// "Options:"
	Options() string
	// "options (array of strings) - answer options for choice type, empty for others"
	OptionsArrayOfStringsAnswerOptionsForChoiceTypeEmptyForOthers() string
	// "Or enter JSON manually"
	OrEnterJsonManually() string
	// "order_index (integer) - position in the quiz (0-based)"
	OrderIndexIntegerPositionInTheQuiz0Based() string
	// "OrUploadOrCreate"
	Oruploadorcreate() string
	// "Overview"
	Overview() string
	// "Owner"
	Owner() string
	// "Page Not Found"
	PageNotFound() string
	// "Password"
	Password() string
	// "PDF Preview"
	PdfPreview() string
	// "Permission granted"
	PermissionGranted() string
	// "Permission revoked"
	PermissionRevoked() string
	// "Permissions"
	Permissions() string
	// "Physics: Mechanics, electricity, optics"
	PhysicsMechanicsElectricityOptics() string
	// "Points"
	Points() string
	// "points (integer) - point value for the question (default 10)"
	PointsIntegerPointValueForTheQuestionDefault10() string
	// "Practice daily to keep your streak. Consistency is the key to success!"
	PracticeDailyToKeepYourStreakConsistencyIsTheKeyToSuccess() string
	// "Preview"
	Preview() string
	// "Preview Not Available"
	PreviewNotAvailable() string
	// "Prompt for LLM question generation"
	PromptForLlmQuestionGeneration() string
	// "Question %d"
	Question(param1 int) string
	// "Question %d of %d"
	QuestionOf(param1 int, param2 int) string
	// "Question Text"
	QuestionText() string
	// "Questions"
	Questions() string
	// "Questions imported successfully"
	QuestionsImportedSuccessfully() string
	// "Quick Actions"
	QuickActions() string
	// "Quiz"
	Quiz() string
	// "Quiz Completed!"
	QuizCompleted() string
	// "Quiz Information"
	QuizInformation() string
	// "Quiz Management"
	QuizManagement() string
	// "Quiz Results"
	QuizResults() string
	// "Quiz saved"
	QuizSaved() string
	// "Quiz statistics"
	QuizStatistics() string
	// "Quizzes"
	Quizzes() string
	// "Quizzes Completed"
	QuizzesCompleted() string
	// "Ready Resource"
	ReadyResource() string
	// "Ready Resource Description"
	ReadyResourceDescription() string
	// "Ready to Start?"
	ReadyToStart() string
	// "Recent Activity"
	RecentActivity() string
	// "Recompile"
	Recompile() string
	// "Registration"
	Registration() string
	// "Remove Admin"
	RemoveAdmin() string
	// "Remove Member"
	RemoveMember() string
	// "Resource"
	Resource() string
	// "Resource File"
	ResourceFile() string
	// "Resource File Help"
	ResourceFileHelp() string
	// "Response must be a VALID JSON array of objects. No additional text."
	ResponseMustBeAValidJsonArrayOfObjectsNoAdditionalText() string
	// "Response must be in JSON format"
	ResponseMustBeInJsonFormat() string
	// "Result"
	Result() string
	// "Results"
	Results() string
	// "Results will appear after students complete quizzes"
	ResultsWillAppearAfterStudentsCompleteQuizzes() string
	// "Resume"
	Resume() string
	// "Resume test"
	ResumeTest() string
	// "Retry"
	Retry() string
	// "Revoke Access"
	RevokeAccess() string
	// "Role updated"
	RoleUpdated() string
	// "Satisfactory"
	Satisfactory() string
	// "Save"
	Save() string
	// "Save All"
	SaveAll() string
	// "Save error"
	SaveError() string
	// "Search by email"
	SearchByEmail() string
	// "Search by name or email"
	SearchByNameOrEmail() string
	// "See correct answers immediately after each question. Learn from your mistakes!"
	SeeCorrectAnswersImmediatelyAfterEachQuestionLearnFromYourMistakes() string
	// "Select group"
	SelectGroup() string
	// "Share"
	Share() string
	// "Sign In"
	SignIn() string
	// "Sign In to Account"
	SignInToAccount() string
	// "Sign Up"
	SignUp() string
	// "Sign Up Free"
	SignUpFree() string
	// "Sorry, the requested page does not exist or has been moved."
	SorryTheRequestedPageDoesNotExistOrHasBeenMoved() string
	// "Start"
	Start() string
	// "Start Free"
	StartFree() string
	// "Statistics"
	Statistics() string
	// "Status"
	Status() string
	// "Streak days in a row"
	StreakDaysInARow() string
	// "Student"
	Student() string
	// "Students by Grade"
	StudentsByGrade() string
	// "Subject"
	Subject() string
	// "Subjects"
	Subjects() string
	// "Submit"
	Submit() string
	// "Success Rate"
	SuccessRate() string
	// "Summary Statistics"
	SummaryStatistics() string
	// "Template Description"
	TemplateDescription() string
	// "Test already active"
	TestAlreadyActive() string
	// "Test conflict"
	TestConflict() string
	// "Test in progress"
	TestInProgress() string
	// "text (string) - question text"
	TextStringQuestionText() string
	// "There are %d unanswered questions! Are you sure you want to end?"
	ThereAreUnansweredQuestionsAreYouSureYouWantToEnd(param1 int) string
	// "Time"
	Time() string
	// "Time (min)"
	TimeMin() string
	// "Time remaining"
	TimeRemaining() string
	// "Title"
	Title() string
	// "To quiz list"
	ToQuizList() string
	// "Topic"
	Topic() string
	// "Total Attempts"
	TotalAttempts() string
	// "Total Points"
	TotalPoints() string
	// "Total Quizzes"
	TotalQuizzes() string
	// "Total Students"
	TotalStudents() string
	// "Total XP"
	TotalXp() string
	// "Try Again"
	TryAgain() string
	// "Type"
	Type() string
	// "type (string) - one of: choice, open, fill"
	TypeStringOneOfChoiceOpenFill() string
	// "Typst Files"
	TypstFiles() string
	// "Typst Files Help"
	TypstFilesHelp() string
	// "Typst Source"
	TypstSource() string
	// "Typst Source Description"
	TypstSourceDescription() string
	// "Unsatisfactory"
	Unsatisfactory() string
	// "Updated At"
	UpdatedAt() string
	// "Upload"
	Upload() string
	// "Upload JSON file"
	UploadJsonFile() string
	// "User"
	User() string
	// "View All"
	ViewAll() string
	// "View student answers"
	ViewStudentAnswers() string
	// "Why GoQuizVibe?"
	WhyGoquizvibe() string
	// "You"
	You() string
	// "You are an expert at creating test questions. Create an array of questions on the topic."
	YouAreAnExpertAtCreatingTestQuestionsCreateAnArrayOfQuestionsOnTheTopic() string
	// "You can edit"
	YouCanEdit() string
	// "You can view"
	YouCanView() string
	// "You have full access"
	YouHaveFullAccess() string
	// "You have no mistakes yet. Keep it up!"
	YouHaveNoMistakesYetKeepItUp() string
	// "Your answer:"
	YourAnswer() string
}

type translator struct {
	locale *gotext.Locale
}

func New(locale Locale) (Translator, error) {
	_, file, _, _ := runtime.Caller(0)
	localesDir := filepath.Dir(file)
	l := gotext.NewLocale(localesDir, string(locale))
	l.AddDomain("default")
	return &translator{locale: l}, nil
}

func (t *translator) Access() string {
	return t.locale.Get("Access")
}

func (t *translator) Actions() string {
	return t.locale.Get("Actions")
}

func (t *translator) Add() string {
	return t.locale.Get("Add")
}

func (t *translator) AddMember() string {
	return t.locale.Get("Add Member")
}

func (t *translator) AddOption() string {
	return t.locale.Get("Add Option")
}

func (t *translator) AddQuestion() string {
	return t.locale.Get("Add Question")
}

func (t *translator) Admin() string {
	return t.locale.Get("Admin")
}

func (t *translator) Admins() string {
	return t.locale.Get("Admins")
}

func (t *translator) All() string {
	return t.locale.Get("All")
}

func (t *translator) AllQuestionsAnsweredEndQuiz() string {
	return t.locale.Get("All Questions Answered! End quiz?")
}

func (t *translator) AllQuizzes() string {
	return t.locale.Get("All Quizzes")
}

func (t *translator) AlreadyHaveAnAccount() string {
	return t.locale.Get("Already have an account?")
}

func (t *translator) AnErrorOccurred() string {
	return t.locale.Get("An error occurred")
}

func (t *translator) Analytics() string {
	return t.locale.Get("Analytics")
}

func (t *translator) AnotherTest() string {
	return t.locale.Get("Another test")
}

func (t *translator) Answer() string {
	return t.locale.Get("Answer:")
}

func (t *translator) AnswerDetails() string {
	return t.locale.Get("Answer Details")
}

func (t *translator) AnswerOptions() string {
	return t.locale.Get("Answer Options")
}

func (t *translator) Archived() string {
	return t.locale.Get("Archived")
}

func (t *translator) AreYouSureThisActionIsReversible() string {
	return t.locale.Get("Are you sure? This action is reversible.")
}

func (t *translator) AreYouSureYouWantToDeleteThisMaterial() string {
	return t.locale.Get("Are you sure you want to delete this material?")
}

func (t *translator) Assigned() string {
	return t.locale.Get("Assigned")
}

func (t *translator) Attempts() string {
	return t.locale.Get("Attempts")
}

func (t *translator) Available() string {
	return t.locale.Get("Available")
}

func (t *translator) AvailableQuizzes() string {
	return t.locale.Get("Available Quizzes")
}

func (t *translator) AverageScore() string {
	return t.locale.Get("Average Score")
}

func (t *translator) AvgScore() string {
	return t.locale.Get("Avg Score")
}

func (t *translator) Back() string {
	return t.locale.Get("Back")
}

func (t *translator) BackTo(param1 string) string {
	return t.locale.Get("Back to %s", param1)
}

func (t *translator) BackToEdit() string {
	return t.locale.Get("Back to Edit")
}

func (t *translator) BackToHome() string {
	return t.locale.Get("Back to Home")
}

func (t *translator) BackToList() string {
	return t.locale.Get("Back to List")
}

func (t *translator) BackToQuizzes() string {
	return t.locale.Get("Back to Quizzes")
}

func (t *translator) CanEdit() string {
	return t.locale.Get("Can Edit")
}

func (t *translator) CanView() string {
	return t.locale.Get("Can View")
}

func (t *translator) Cancel() string {
	return t.locale.Get("Cancel")
}

func (t *translator) CancelAndStartNew() string {
	return t.locale.Get("Cancel and start new")
}

func (t *translator) CancellingWillCompleteTheCurrentTestWithYourCurrentAnswersThisActionCannotBeUndone() string {
	return t.locale.Get("Cancelling will complete the current test with your current answers. This action cannot be undone.")
}

func (t *translator) CheckResults() string {
	return t.locale.Get("Check Results")
}

func (t *translator) ChemistryOrganicAndInorganic() string {
	return t.locale.Get("Chemistry: Organic and inorganic")
}

func (t *translator) Choice() string {
	return t.locale.Get("Choice")
}

func (t *translator) Class() string {
	return t.locale.Get("Class")
}

func (t *translator) CompeteWithClassmatesWeeklyRatingsAndBonusRewards() string {
	return t.locale.Get("Compete with classmates. Weekly ratings and bonus rewards!")
}

func (t *translator) Completed() string {
	return t.locale.Get("Completed")
}

func (t *translator) ControlPanel() string {
	return t.locale.Get("Control Panel")
}

func (t *translator) Copyright2026Goquizvibe() string {
	return t.locale.Get("Copyright 2026 GoQuizVibe")
}

func (t *translator) Correct() string {
	return t.locale.Get("Correct")
}

func (t *translator) CorrectAnswer() string {
	return t.locale.Get("Correct Answer")
}

func (t *translator) CorrectAnswerStringCorrectAnswer() string {
	return t.locale.Get("correct_answer (string) - correct answer")
}

func (t *translator) Create() string {
	return t.locale.Get("Create")
}

func (t *translator) CreateFirstLearningMaterial() string {
	return t.locale.Get("Create First Learning Material")
}

func (t *translator) CreateFirstQuiz() string {
	return t.locale.Get("Create first quiz")
}

func (t *translator) CreateFromTemplate() string {
	return t.locale.Get("Create from Template")
}

func (t *translator) CreateGroup() string {
	return t.locale.Get("Create Group")
}

func (t *translator) CreateLearningMaterial() string {
	return t.locale.Get("Create Learning Material")
}

func (t *translator) CreateQuiz() string {
	return t.locale.Get("Create Quiz")
}

func (t *translator) CreatedAt() string {
	return t.locale.Get("Created At")
}

func (t *translator) DangerZone() string {
	return t.locale.Get("Danger Zone")
}

func (t *translator) Dashboard() string {
	return t.locale.Get("Dashboard")
}

func (t *translator) Date() string {
	return t.locale.Get("Date")
}

func (t *translator) DayStreak() string {
	return t.locale.Get("day streak")
}

func (t *translator) Delete() string {
	return t.locale.Get("Delete")
}

func (t *translator) DeleteGroup() string {
	return t.locale.Get("Delete Group")
}

func (t *translator) DeleteImage() string {
	return t.locale.Get("Delete image?")
}

func (t *translator) DeleteQuestion() string {
	return t.locale.Get("Delete question?")
}

func (t *translator) DeleteQuiz() string {
	return t.locale.Get("Delete quiz?")
}

func (t *translator) Description() string {
	return t.locale.Get("Description")
}

func (t *translator) DownloadPromptAsFile() string {
	return t.locale.Get("Download Prompt as File")
}

func (t *translator) EachQuestionMustContainTheFollowingFields() string {
	return t.locale.Get("Each question must contain the following fields:")
}

func (t *translator) Edit() string {
	return t.locale.Get("Edit")
}

func (t *translator) Editing(param1 string) string {
	return t.locale.Get("Editing: %s", param1)
}

func (t *translator) Email() string {
	return t.locale.Get("Email")
}

func (t *translator) EndQuizThisActionCannotBeUndone() string {
	return t.locale.Get("End quiz? This action cannot be undone.")
}

func (t *translator) EnterQuizTopicAboveToGeneratePrompt() string {
	return t.locale.Get("Enter quiz topic above to generate prompt")
}

func (t *translator) EnterYourAnswer() string {
	return t.locale.Get("Enter your answer...")
}

func (t *translator) Error() string {
	return t.locale.Get("Error")
}

func (t *translator) Excellent() string {
	return t.locale.Get("Excellent")
}

func (t *translator) ExperiencePoints() string {
	return t.locale.Get("experience points")
}

func (t *translator) Explanation() string {
	return t.locale.Get("Explanation:")
}

func (t *translator) ExplanationStringExplanationForTheAnswer() string {
	return t.locale.Get("explanation (string) - explanation for the answer")
}

func (t *translator) FailedToImportQuestions() string {
	return t.locale.Get("Failed to import questions")
}

func (t *translator) FileSize() string {
	return t.locale.Get("File Size")
}

func (t *translator) Fill() string {
	return t.locale.Get("Fill")
}

func (t *translator) FilterByQuiz() string {
	return t.locale.Get("Filter by Quiz")
}

func (t *translator) ForStudents() string {
	return t.locale.Get("For Students")
}

func (t *translator) Good() string {
	return t.locale.Get("Good")
}

func (t *translator) GoquizvibeAdmin() string {
	return t.locale.Get("GoQuizVibe Admin")
}

func (t *translator) Grade() string {
	return t.locale.Get("grade")
}

func (t *translator) GrantAccess() string {
	return t.locale.Get("Grant Access")
}

func (t *translator) GreatJob() string {
	return t.locale.Get("Great job!")
}

func (t *translator) Group() string {
	return t.locale.Get("Group")
}

func (t *translator) GroupCreated() string {
	return t.locale.Get("Group created")
}

func (t *translator) GroupDeleted() string {
	return t.locale.Get("Group deleted")
}

func (t *translator) GroupName() string {
	return t.locale.Get("Group Name")
}

func (t *translator) GroupUpdated() string {
	return t.locale.Get("Group updated")
}

func (t *translator) ImagesUpTo3() string {
	return t.locale.Get("Images (up to 3)")
}

func (t *translator) Import() string {
	return t.locale.Get("Import")
}

func (t *translator) ImportFromJson() string {
	return t.locale.Get("Import from JSON")
}

func (t *translator) ImportQuestions() string {
	return t.locale.Get("Import Questions")
}

func (t *translator) InteractiveExamPreparationPlatformWithGamificationEarnXpMaintainStreaksAndCompeteWithFriends() string {
	return t.locale.Get("Interactive exam preparation platform with gamification. Earn XP, maintain streaks, and compete with friends!")
}

func (t *translator) InvalidJsonFormat() string {
	return t.locale.Get("Invalid JSON format")
}

func (t *translator) JoinThousandsOfStudentsWhoAreAlreadyLearningWithJoy() string {
	return t.locale.Get("Join thousands of students who are already learning with joy!")
}

func (t *translator) JpgPngWebpUpTo5mbEach() string {
	return t.locale.Get("JPG, PNG, WebP up to 5MB each")
}

func (t *translator) JsonSchemaForQuestionObject() string {
	return t.locale.Get("JSON Schema for question object")
}

func (t *translator) JsonStructureForQuestion() string {
	return t.locale.Get("JSON structure for question:")
}

func (t *translator) Language() string {
	return t.locale.Get("Language")
}

func (t *translator) Leaderboard() string {
	return t.locale.Get("Leaderboard")
}

func (t *translator) Leaders() string {
	return t.locale.Get("Leaders")
}

func (t *translator) LearnThroughPlay() string {
	return t.locale.Get("Learn Through Play")
}

func (t *translator) LearningMaterialDescriptionPlaceholder() string {
	return t.locale.Get("Learning Material Description Placeholder")
}

func (t *translator) LearningMaterialTitlePlaceholder() string {
	return t.locale.Get("Learning Material Title Placeholder")
}

func (t *translator) LearningMaterials() string {
	return t.locale.Get("Learning Materials")
}

func (t *translator) LeaveGroup() string {
	return t.locale.Get("Leave Group")
}

func (t *translator) LeftGroup() string {
	return t.locale.Get("Left group")
}

func (t *translator) Loading() string {
	return t.locale.Get("Loading...")
}

func (t *translator) LogIn() string {
	return t.locale.Get("Log In")
}

func (t *translator) Made() string {
	return t.locale.Get("made")
}

func (t *translator) MakeAdmin() string {
	return t.locale.Get("Make Admin")
}

func (t *translator) MaterialType() string {
	return t.locale.Get("Material Type")
}

func (t *translator) MathFromBasicArithmeticToAlgebra() string {
	return t.locale.Get("Math: From basic arithmetic to algebra")
}

func (t *translator) Member() string {
	return t.locale.Get("Member")
}

func (t *translator) MemberAdded() string {
	return t.locale.Get("Member added")
}

func (t *translator) MemberRemoved() string {
	return t.locale.Get("Member removed")
}

func (t *translator) Members() string {
	return t.locale.Get("Members")
}

func (t *translator) MimeType() string {
	return t.locale.Get("Mime Type")
}

func (t *translator) Min() string {
	return t.locale.Get("min")
}

func (t *translator) Minimum6Characters() string {
	return t.locale.Get("Minimum 6 characters")
}

func (t *translator) Mistake() string {
	return t.locale.Get("Mistake")
}

func (t *translator) MistakeReview() string {
	return t.locale.Get("Mistake Review")
}

func (t *translator) Mistakes() string {
	return t.locale.Get("Mistakes")
}

func (t *translator) MistakesMade() string {
	return t.locale.Get("Mistakes Made")
}

func (t *translator) MoveToArchive() string {
	return t.locale.Get("Move to Archive")
}

func (t *translator) MyGroups() string {
	return t.locale.Get("My Groups")
}

func (t *translator) Name() string {
	return t.locale.Get("Name")
}

func (t *translator) NewQuestion() string {
	return t.locale.Get("New Question")
}

func (t *translator) NewQuizWithQuestions() string {
	return t.locale.Get("New quiz with questions")
}

func (t *translator) NoAccess() string {
	return t.locale.Get("No access")
}

func (t *translator) NoAccount() string {
	return t.locale.Get("No account?")
}

func (t *translator) NoActivityYet() string {
	return t.locale.Get("No activity yet")
}

func (t *translator) NoDataYet() string {
	return t.locale.Get("No data yet")
}

func (t *translator) NoGroupsYet() string {
	return t.locale.Get("No groups yet")
}

func (t *translator) NoLearningMaterialsAvailable() string {
	return t.locale.Get("No Learning Materials Available")
}

func (t *translator) NoMaterialsYet() string {
	return t.locale.Get("No Materials Yet")
}

func (t *translator) NoParticipantsYet() string {
	return t.locale.Get("No participants yet")
}

func (t *translator) NoPermissionsYet() string {
	return t.locale.Get("No permissions yet")
}

func (t *translator) NoPreviewAvailable() string {
	return t.locale.Get("No Preview Available")
}

func (t *translator) NoQuestionsYet() string {
	return t.locale.Get("No questions yet")
}

func (t *translator) NoQuizzesAvailableYet() string {
	return t.locale.Get("No quizzes available yet")
}

func (t *translator) NoResultsYet() string {
	return t.locale.Get("No results yet")
}

func (t *translator) Open() string {
	return t.locale.Get("Open")
}

func (t *translator) OpenInNewTab() string {
	return t.locale.Get("Open in New Tab")
}

func (t *translator) OpenResource() string {
	return t.locale.Get("Open Resource")
}

func (t *translator) Options() string {
	return t.locale.Get("Options:")
}

func (t *translator) OptionsArrayOfStringsAnswerOptionsForChoiceTypeEmptyForOthers() string {
	return t.locale.Get("options (array of strings) - answer options for choice type, empty for others")
}

func (t *translator) OrEnterJsonManually() string {
	return t.locale.Get("Or enter JSON manually")
}

func (t *translator) OrderIndexIntegerPositionInTheQuiz0Based() string {
	return t.locale.Get("order_index (integer) - position in the quiz (0-based)")
}

func (t *translator) Oruploadorcreate() string {
	return t.locale.Get("OrUploadOrCreate")
}

func (t *translator) Overview() string {
	return t.locale.Get("Overview")
}

func (t *translator) Owner() string {
	return t.locale.Get("Owner")
}

func (t *translator) PageNotFound() string {
	return t.locale.Get("Page Not Found")
}

func (t *translator) Password() string {
	return t.locale.Get("Password")
}

func (t *translator) PdfPreview() string {
	return t.locale.Get("PDF Preview")
}

func (t *translator) PermissionGranted() string {
	return t.locale.Get("Permission granted")
}

func (t *translator) PermissionRevoked() string {
	return t.locale.Get("Permission revoked")
}

func (t *translator) Permissions() string {
	return t.locale.Get("Permissions")
}

func (t *translator) PhysicsMechanicsElectricityOptics() string {
	return t.locale.Get("Physics: Mechanics, electricity, optics")
}

func (t *translator) Points() string {
	return t.locale.Get("Points")
}

func (t *translator) PointsIntegerPointValueForTheQuestionDefault10() string {
	return t.locale.Get("points (integer) - point value for the question (default 10)")
}

func (t *translator) PracticeDailyToKeepYourStreakConsistencyIsTheKeyToSuccess() string {
	return t.locale.Get("Practice daily to keep your streak. Consistency is the key to success!")
}

func (t *translator) Preview() string {
	return t.locale.Get("Preview")
}

func (t *translator) PreviewNotAvailable() string {
	return t.locale.Get("Preview Not Available")
}

func (t *translator) PromptForLlmQuestionGeneration() string {
	return t.locale.Get("Prompt for LLM question generation")
}

func (t *translator) Question(param1 int) string {
	return t.locale.Get("Question %d", param1)
}

func (t *translator) QuestionOf(param1 int, param2 int) string {
	return t.locale.Get("Question %d of %d", param1, param2)
}

func (t *translator) QuestionText() string {
	return t.locale.Get("Question Text")
}

func (t *translator) Questions() string {
	return t.locale.Get("Questions")
}

func (t *translator) QuestionsImportedSuccessfully() string {
	return t.locale.Get("Questions imported successfully")
}

func (t *translator) QuickActions() string {
	return t.locale.Get("Quick Actions")
}

func (t *translator) Quiz() string {
	return t.locale.Get("Quiz")
}

func (t *translator) QuizCompleted() string {
	return t.locale.Get("Quiz Completed!")
}

func (t *translator) QuizInformation() string {
	return t.locale.Get("Quiz Information")
}

func (t *translator) QuizManagement() string {
	return t.locale.Get("Quiz Management")
}

func (t *translator) QuizResults() string {
	return t.locale.Get("Quiz Results")
}

func (t *translator) QuizSaved() string {
	return t.locale.Get("Quiz saved")
}

func (t *translator) QuizStatistics() string {
	return t.locale.Get("Quiz statistics")
}

func (t *translator) Quizzes() string {
	return t.locale.Get("Quizzes")
}

func (t *translator) QuizzesCompleted() string {
	return t.locale.Get("Quizzes Completed")
}

func (t *translator) ReadyResource() string {
	return t.locale.Get("Ready Resource")
}

func (t *translator) ReadyResourceDescription() string {
	return t.locale.Get("Ready Resource Description")
}

func (t *translator) ReadyToStart() string {
	return t.locale.Get("Ready to Start?")
}

func (t *translator) RecentActivity() string {
	return t.locale.Get("Recent Activity")
}

func (t *translator) Recompile() string {
	return t.locale.Get("Recompile")
}

func (t *translator) Registration() string {
	return t.locale.Get("Registration")
}

func (t *translator) RemoveAdmin() string {
	return t.locale.Get("Remove Admin")
}

func (t *translator) RemoveMember() string {
	return t.locale.Get("Remove Member")
}

func (t *translator) Resource() string {
	return t.locale.Get("Resource")
}

func (t *translator) ResourceFile() string {
	return t.locale.Get("Resource File")
}

func (t *translator) ResourceFileHelp() string {
	return t.locale.Get("Resource File Help")
}

func (t *translator) ResponseMustBeAValidJsonArrayOfObjectsNoAdditionalText() string {
	return t.locale.Get("Response must be a VALID JSON array of objects. No additional text.")
}

func (t *translator) ResponseMustBeInJsonFormat() string {
	return t.locale.Get("Response must be in JSON format")
}

func (t *translator) Result() string {
	return t.locale.Get("Result")
}

func (t *translator) Results() string {
	return t.locale.Get("Results")
}

func (t *translator) ResultsWillAppearAfterStudentsCompleteQuizzes() string {
	return t.locale.Get("Results will appear after students complete quizzes")
}

func (t *translator) Resume() string {
	return t.locale.Get("Resume")
}

func (t *translator) ResumeTest() string {
	return t.locale.Get("Resume test")
}

func (t *translator) Retry() string {
	return t.locale.Get("Retry")
}

func (t *translator) RevokeAccess() string {
	return t.locale.Get("Revoke Access")
}

func (t *translator) RoleUpdated() string {
	return t.locale.Get("Role updated")
}

func (t *translator) Satisfactory() string {
	return t.locale.Get("Satisfactory")
}

func (t *translator) Save() string {
	return t.locale.Get("Save")
}

func (t *translator) SaveAll() string {
	return t.locale.Get("Save All")
}

func (t *translator) SaveError() string {
	return t.locale.Get("Save error")
}

func (t *translator) SearchByEmail() string {
	return t.locale.Get("Search by email")
}

func (t *translator) SearchByNameOrEmail() string {
	return t.locale.Get("Search by name or email")
}

func (t *translator) SeeCorrectAnswersImmediatelyAfterEachQuestionLearnFromYourMistakes() string {
	return t.locale.Get("See correct answers immediately after each question. Learn from your mistakes!")
}

func (t *translator) SelectGroup() string {
	return t.locale.Get("Select group")
}

func (t *translator) Share() string {
	return t.locale.Get("Share")
}

func (t *translator) SignIn() string {
	return t.locale.Get("Sign In")
}

func (t *translator) SignInToAccount() string {
	return t.locale.Get("Sign In to Account")
}

func (t *translator) SignUp() string {
	return t.locale.Get("Sign Up")
}

func (t *translator) SignUpFree() string {
	return t.locale.Get("Sign Up Free")
}

func (t *translator) SorryTheRequestedPageDoesNotExistOrHasBeenMoved() string {
	return t.locale.Get("Sorry, the requested page does not exist or has been moved.")
}

func (t *translator) Start() string {
	return t.locale.Get("Start")
}

func (t *translator) StartFree() string {
	return t.locale.Get("Start Free")
}

func (t *translator) Statistics() string {
	return t.locale.Get("Statistics")
}

func (t *translator) Status() string {
	return t.locale.Get("Status")
}

func (t *translator) StreakDaysInARow() string {
	return t.locale.Get("Streak days in a row")
}

func (t *translator) Student() string {
	return t.locale.Get("Student")
}

func (t *translator) StudentsByGrade() string {
	return t.locale.Get("Students by Grade")
}

func (t *translator) Subject() string {
	return t.locale.Get("Subject")
}

func (t *translator) Subjects() string {
	return t.locale.Get("Subjects")
}

func (t *translator) Submit() string {
	return t.locale.Get("Submit")
}

func (t *translator) SuccessRate() string {
	return t.locale.Get("Success Rate")
}

func (t *translator) SummaryStatistics() string {
	return t.locale.Get("Summary Statistics")
}

func (t *translator) TemplateDescription() string {
	return t.locale.Get("Template Description")
}

func (t *translator) TestAlreadyActive() string {
	return t.locale.Get("Test already active")
}

func (t *translator) TestConflict() string {
	return t.locale.Get("Test conflict")
}

func (t *translator) TestInProgress() string {
	return t.locale.Get("Test in progress")
}

func (t *translator) TextStringQuestionText() string {
	return t.locale.Get("text (string) - question text")
}

func (t *translator) ThereAreUnansweredQuestionsAreYouSureYouWantToEnd(param1 int) string {
	return t.locale.Get("There are %d unanswered questions! Are you sure you want to end?", param1)
}

func (t *translator) Time() string {
	return t.locale.Get("Time")
}

func (t *translator) TimeMin() string {
	return t.locale.Get("Time (min)")
}

func (t *translator) TimeRemaining() string {
	return t.locale.Get("Time remaining")
}

func (t *translator) Title() string {
	return t.locale.Get("Title")
}

func (t *translator) ToQuizList() string {
	return t.locale.Get("To quiz list")
}

func (t *translator) Topic() string {
	return t.locale.Get("Topic")
}

func (t *translator) TotalAttempts() string {
	return t.locale.Get("Total Attempts")
}

func (t *translator) TotalPoints() string {
	return t.locale.Get("Total Points")
}

func (t *translator) TotalQuizzes() string {
	return t.locale.Get("Total Quizzes")
}

func (t *translator) TotalStudents() string {
	return t.locale.Get("Total Students")
}

func (t *translator) TotalXp() string {
	return t.locale.Get("Total XP")
}

func (t *translator) TryAgain() string {
	return t.locale.Get("Try Again")
}

func (t *translator) Type() string {
	return t.locale.Get("Type")
}

func (t *translator) TypeStringOneOfChoiceOpenFill() string {
	return t.locale.Get("type (string) - one of: choice, open, fill")
}

func (t *translator) TypstFiles() string {
	return t.locale.Get("Typst Files")
}

func (t *translator) TypstFilesHelp() string {
	return t.locale.Get("Typst Files Help")
}

func (t *translator) TypstSource() string {
	return t.locale.Get("Typst Source")
}

func (t *translator) TypstSourceDescription() string {
	return t.locale.Get("Typst Source Description")
}

func (t *translator) Unsatisfactory() string {
	return t.locale.Get("Unsatisfactory")
}

func (t *translator) UpdatedAt() string {
	return t.locale.Get("Updated At")
}

func (t *translator) Upload() string {
	return t.locale.Get("Upload")
}

func (t *translator) UploadJsonFile() string {
	return t.locale.Get("Upload JSON file")
}

func (t *translator) User() string {
	return t.locale.Get("User")
}

func (t *translator) ViewAll() string {
	return t.locale.Get("View All")
}

func (t *translator) ViewStudentAnswers() string {
	return t.locale.Get("View student answers")
}

func (t *translator) WhyGoquizvibe() string {
	return t.locale.Get("Why GoQuizVibe?")
}

func (t *translator) You() string {
	return t.locale.Get("You")
}

func (t *translator) YouAreAnExpertAtCreatingTestQuestionsCreateAnArrayOfQuestionsOnTheTopic() string {
	return t.locale.Get("You are an expert at creating test questions. Create an array of questions on the topic.")
}

func (t *translator) YouCanEdit() string {
	return t.locale.Get("You can edit")
}

func (t *translator) YouCanView() string {
	return t.locale.Get("You can view")
}

func (t *translator) YouHaveFullAccess() string {
	return t.locale.Get("You have full access")
}

func (t *translator) YouHaveNoMistakesYetKeepItUp() string {
	return t.locale.Get("You have no mistakes yet. Keep it up!")
}

func (t *translator) YourAnswer() string {
	return t.locale.Get("Your answer:")
}

